; Generated by c86 (BYU-NASM) 5.1 (beta) from yakc.i
	CPU	8086
	ALIGN	2
	jmp	main	; Jump to program start
	ALIGN	2
YKIdleTask:
	; >>>>> Line:	16
	; >>>>> void YKIdleTask(void) { 
	jmp	L_yakc_1
L_yakc_2:
	; >>>>> Line:	18
	; >>>>> while(1){ 
	jmp	L_yakc_4
L_yakc_3:
	; >>>>> Line:	19
	; >>>>> ++dummy; 
	inc	word [bp-2]
	; >>>>> Line:	20
	; >>>>> --dummy; 
	dec	word [bp-2]
	; >>>>> Line:	21
	; >>>>> ++dummy; 
	inc	word [bp-2]
	; >>>>> Line:	22
	; >>>>> ++YKIdleCount; 
	inc	word [YKIdleCount]
L_yakc_4:
	jmp	L_yakc_3
L_yakc_5:
	mov	sp, bp
	pop	bp
	ret
L_yakc_1:
	push	bp
	mov	bp, sp
	push	cx
	jmp	L_yakc_2
	ALIGN	2
YKInitialize:
	; >>>>> Line:	26
	; >>>>> void YKInitialize(void) { 
	jmp	L_yakc_7
L_yakc_8:
	; >>>>> Line:	30
	; >>>>> YKCtxSwCount = 0; 
	mov	word [bp-6], 100
	; >>>>> Line:	30
	; >>>>> YKCtxSwCount = 0; 
	mov	word [YKCtxSwCount], 0
	; >>>>> Line:	31
	; >>>>> YKTickNum = 0; 
	mov	word [YKTickNum], 0
	; >>>>> Line:	32
	; >>>>> YKIdleCount = 0; 
	mov	word [YKIdleCount], 0
	; >>>>> Line:	33
	; >>>>> YKISRDepth = 0; 
	mov	word [YKISRDepth], 0
	; >>>>> Line:	34
	; >>>>> YKRunFlag = 0; 
	mov	word [YKRunFlag], 0
	; >>>>> Line:	35
	; >>>>> YKBlockList = 0; 
	mov	word [YKBlockList], 0
	; >>>>> Line:	36
	; >>>>> YKRdyList = 0; 
	mov	word [YKRdyList], 0
	; >>>>> Line:	37
	; >>>>> YKCurrTask = 0; 
	mov	word [YKCurrTask], 0
	; >>>>> Line:	38
	; >>>>> idle_task_p = YKIdleTask; 
	mov	word [bp-2], YKIdleTask
	; >>>>> Line:	39
	; >>>>> idle_task_stack_p = YKIdleTaskStack + 256 - 1; 
	mov	word [bp-4], (YKIdleTaskStack--510)
	; >>>>> Line:	40
	; >>>>> lowest_priority = 100; 
	mov	word [bp-6], 100
	; >>>>> Line:	42
	; >>>>> YKAvailTCBList = YKTCBArray; 
	mov	word [YKAvailTCBList], YKTCBArray
	; >>>>> Line:	43
	; >>>>> YKNewTask(idle_task_p, idle_task_stack_p, lowest_priority); 
	push	word [bp-6]
	push	word [bp-4]
	push	word [bp-2]
	call	YKNewTask
	add	sp, 6
	mov	sp, bp
	pop	bp
	ret
L_yakc_7:
	push	bp
	mov	bp, sp
	sub	sp, 6
	jmp	L_yakc_8
	ALIGN	2
YKNewTask:
	; >>>>> Line:	50
	; >>>>> void YKNewTask(void (* task)(void), void *taskStack, unsigned char priority) { 
	jmp	L_yakc_10
L_yakc_11:
	; >>>>> Line:	52
	; >>>>> YKAvailTCBList++; 
	mov	ax, word [YKAvailTCBList]
	mov	word [bp-2], ax
	; >>>>> Line:	52
	; >>>>> YKAvailTCBList++; 
	add	word [YKAvailTCBList], 38
	; >>>>> Line:	53
	; >>>>> cur_tcb->ax = 0; 
	mov	si, word [bp-2]
	mov	word [si], 0
	; >>>>> Line:	54
	; >>>>> cur_tcb->bx = 0; 
	mov	si, word [bp-2]
	add	si, 2
	mov	word [si], 0
	; >>>>> Line:	55
	; >>>>> cur_tcb->cx = 0; 
	mov	si, word [bp-2]
	add	si, 4
	mov	word [si], 0
	; >>>>> Line:	56
	; >>>>> cur_tcb->dx = 0; 
	mov	si, word [bp-2]
	add	si, 6
	mov	word [si], 0
	; >>>>> Line:	57
	; >>>>> cur_tcb->ip = task; 
	mov	si, word [bp-2]
	add	si, 8
	mov	ax, word [bp+4]
	mov	word [si], ax
	; >>>>> Line:	58
	; >>>>> cur_tcb->sp = taskStack; 
	mov	si, word [bp-2]
	add	si, 10
	mov	ax, word [bp+6]
	mov	word [si], ax
	; >>>>> Line:	59
	; >>>>> cur_tcb->bp = taskStack; 
	mov	si, word [bp-2]
	add	si, 12
	mov	ax, word [bp+6]
	mov	word [si], ax
	; >>>>> Line:	60
	; >>>>> cur_tcb->si = 0; 
	mov	si, word [bp-2]
	add	si, 14
	mov	word [si], 0
	; >>>>> Line:	61
	; >>>>> cur_tcb->di = 0; 
	mov	si, word [bp-2]
	add	si, 16
	mov	word [si], 0
	; >>>>> Line:	62
	; >>>>> cur_tcb->cs = 0; 
	mov	si, word [bp-2]
	add	si, 18
	mov	word [si], 0
	; >>>>> Line:	63
	; >>>>> cur_tcb->ss = 0; 
	mov	si, word [bp-2]
	add	si, 20
	mov	word [si], 0
	; >>>>> Line:	64
	; >>>>> cur_tcb->ds = 0; 
	mov	si, word [bp-2]
	add	si, 22
	mov	word [si], 0
	; >>>>> Line:	65
	; >>>>> cur_tcb->es = 0; 
	mov	si, word [bp-2]
	add	si, 24
	mov	word [si], 0
	; >>>>> Line:	66
	; >>>>> cur_tcb->flags = 512; 
	mov	si, word [bp-2]
	add	si, 26
	mov	word [si], 512
	; >>>>> Line:	67
	; >>>>> cur_tcb->priority = priority; 
	mov	al, byte [bp+8]
	xor	ah, ah
	mov	si, word [bp-2]
	add	si, 28
	mov	word [si], ax
	; >>>>> Line:	68
	; >>>>> cur_tcb->state = READY; 
	mov	si, word [bp-2]
	add	si, 30
	mov	word [si], 0
	; >>>>> Line:	69
	; >>>>> cur_tcb->delay = 0; 
	mov	si, word [bp-2]
	add	si, 32
	mov	word [si], 0
	; >>>>> Line:	70
	; >>>>> cur_tcb->prev = 0; 
	mov	si, word [bp-2]
	add	si, 34
	mov	word [si], 0
	; >>>>> Line:	71
	; >>>>> cur_tcb->next = 0; 
	mov	si, word [bp-2]
	add	si, 36
	mov	word [si], 0
	; >>>>> Line:	72
	; >>>>> YKAddReadyTask(cur_tcb); 
	push	word [bp-2]
	call	YKAddReadyTask
	add	sp, 2
	; >>>>> Line:	74
	; >>>>> if ( 
	mov	ax, word [YKRunFlag]
	test	ax, ax
	je	L_yakc_12
	; >>>>> Line:	75
	; >>>>> YKScheduler(); 
	call	YKScheduler
L_yakc_12:
	mov	sp, bp
	pop	bp
	ret
L_yakc_10:
	push	bp
	mov	bp, sp
	push	cx
	jmp	L_yakc_11
	ALIGN	2
YKRun:
	; >>>>> Line:	79
	; >>>>> void YKRun(void) { 
	jmp	L_yakc_14
L_yakc_15:
	; >>>>> Line:	80
	; >>>>> YKRunFlag = 1; 
	mov	word [YKRunFlag], 1
	; >>>>> Line:	81
	; >>>>> YKScheduler(); 
	call	YKScheduler
	mov	sp, bp
	pop	bp
	ret
L_yakc_14:
	push	bp
	mov	bp, sp
	jmp	L_yakc_15
	ALIGN	2
YKScheduler:
	; >>>>> Line:	84
	; >>>>> void YKScheduler(void) { 
	jmp	L_yakc_17
L_yakc_18:
	; >>>>> Line:	85
	; >>>>> if (YKCurrTask != YKRdyList) { 
	mov	ax, word [YKRdyList]
	cmp	ax, word [YKCurrTask]
	je	L_yakc_19
	; >>>>> Line:	92
	; >>>>> YKDispatcher(); 
	call	YKDispatcher
L_yakc_19:
	mov	sp, bp
	pop	bp
	ret
L_yakc_17:
	push	bp
	mov	bp, sp
	jmp	L_yakc_18
	ALIGN	2
YKAddReadyTask:
	; >>>>> Line:	97
	; >>>>> void YKAddReadyTask(tcb_t *cur_tcb) { 
	jmp	L_yakc_21
L_yakc_22:
	; >>>>> Line:	98
	; >>>>> if(YKRdyList == 0) { 
	mov	ax, word [YKRdyList]
	test	ax, ax
	jne	L_yakc_23
	; >>>>> Line:	99
	; >>>>> YKRdyList = cur_tcb; 
	mov	ax, word [bp+4]
	mov	word [YKRdyList], ax
	jmp	L_yakc_24
L_yakc_23:
	; >>>>> Line:	104
	; >>>>> while (cur_tcb->priority > iter->priority) { 
	mov	ax, word [YKRdyList]
	mov	word [bp-2], ax
	mov	word [bp-4], 1
	; >>>>> Line:	104
	; >>>>> while (cur_tcb->priority > iter->priority) { 
	jmp	L_yakc_26
L_yakc_25:
	; >>>>> Line:	105
	; >>>>> iter = iter->next; 
	mov	si, word [bp-2]
	add	si, 36
	mov	ax, word [si]
	mov	word [bp-2], ax
	; >>>>> Line:	106
	; >>>>> moved_to_top = 0; 
	mov	word [bp-4], 0
L_yakc_26:
	mov	si, word [bp+4]
	add	si, 28
	mov	di, word [bp-2]
	add	di, 28
	mov	ax, word [di]
	cmp	ax, word [si]
	jl	L_yakc_25
L_yakc_27:
	; >>>>> Line:	108
	; >>>>> tcb_t *it 
	mov	si, word [bp+4]
	add	si, 36
	mov	ax, word [bp-2]
	mov	word [si], ax
	; >>>>> Line:	109
	; >>>>> if (iter->prev) 
	mov	si, word [bp-2]
	add	si, 34
	mov	ax, word [si]
	test	ax, ax
	je	L_yakc_28
	; >>>>> Line:	110
	; >>>>> iter->prev->next = cur_tcb; 
	mov	si, word [bp-2]
	add	si, 34
	mov	si, word [si]
	add	si, 36
	mov	ax, word [bp+4]
	mov	word [si], ax
L_yakc_28:
	; >>>>> Line:	112
	; >>>>> cur_tcb->prev = iter->prev; 
	mov	si, word [bp-2]
	add	si, 34
	mov	di, word [bp+4]
	add	di, 34
	mov	ax, word [si]
	mov	word [di], ax
	; >>>>> Line:	113
	; >>>>> iter->prev = cur_tcb; 
	mov	si, word [bp-2]
	add	si, 34
	mov	ax, word [bp+4]
	mov	word [si], ax
	; >>>>> Line:	115
	; >>>>> if (moved_to_top) 
	mov	ax, word [bp-4]
	test	ax, ax
	je	L_yakc_29
	; >>>>> Line:	116
	; >>>>> YKRdyList = cur_tcb; 
	mov	ax, word [bp+4]
	mov	word [YKRdyList], ax
L_yakc_29:
L_yakc_24:
L_yakc_30:
	; >>>>> Line:	118
	; >>>>> return; 
	mov	sp, bp
	pop	bp
	ret
L_yakc_21:
	push	bp
	mov	bp, sp
	sub	sp, 4
	jmp	L_yakc_22
	ALIGN	2
YKDelayTask:
	; >>>>> Line:	121
	; >>>>> void YKDelayTask(unsigned count) { 
	jmp	L_yakc_32
L_yakc_33:
	; >>>>> Line:	123
	; >>>>> YKCurrTask->delay = count; 
	mov	si, word [YKCurrTask]
	add	si, 32
	mov	ax, word [bp+4]
	mov	word [si], ax
	; >>>>> Line:	124
	; >>>>> YKCurrTask->state = DELAYED; 
	mov	si, word [YKCurrTask]
	add	si, 30
	mov	word [si], 1
	; >>>>> Line:	127
	; >>>>> YKRdyList = YKCurrTask->next; 
	mov	si, word [YKCurrTask]
	add	si, 36
	mov	ax, word [si]
	mov	word [YKRdyList], ax
	; >>>>> Line:	128
	; >>>>> YKRdyList->prev = 0; 
	mov	si, word [YKRdyList]
	add	si, 34
	mov	word [si], 0
	; >>>>> Line:	131
	; >>>>> if (YKBlockList == 0) { 
	mov	ax, word [YKBlockList]
	test	ax, ax
	jne	L_yakc_34
	; >>>>> Line:	132
	; >>>>> YKBlockList = YKCurrTask; 
	mov	ax, word [YKCurrTask]
	mov	word [YKBlockList], ax
	; >>>>> Line:	133
	; >>>>> YKBlockList->next = 0; 
	mov	si, word [YKBlockList]
	add	si, 36
	mov	word [si], 0
	jmp	L_yakc_35
L_yakc_34:
	; >>>>> Line:	138
	; >>>>> while (YKCurrTask->priority > iter->priority) { 
	mov	ax, word [YKBlockList]
	mov	word [bp-2], ax
	mov	word [bp-4], 1
	; >>>>> Line:	138
	; >>>>> while (YKCurrTask->priority > iter->priority) { 
	jmp	L_yakc_37
L_yakc_36:
	; >>>>> Line:	139
	; >>>>> iter = iter->next; 
	mov	si, word [bp-2]
	add	si, 36
	mov	ax, word [si]
	mov	word [bp-2], ax
	; >>>>> Line:	140
	; >>>>> moved_to_top = 0; 
	mov	word [bp-4], 0
L_yakc_37:
	mov	si, word [YKCurrTask]
	add	si, 28
	mov	di, word [bp-2]
	add	di, 28
	mov	ax, word [di]
	cmp	ax, word [si]
	jl	L_yakc_36
L_yakc_38:
	; >>>>> Line:	142
	; >>>>> YKCurrTask->next = iter; 
	mov	si, word [YKCurrTask]
	add	si, 36
	mov	ax, word [bp-2]
	mov	word [si], ax
	; >>>>> Line:	143
	; >>>>> if (iter->prev) 
	mov	si, word [bp-2]
	add	si, 34
	mov	ax, word [si]
	test	ax, ax
	je	L_yakc_39
	; >>>>> Line:	144
	; >>>>> iter->prev->next = YKCurrTask; 
	mov	si, word [bp-2]
	add	si, 34
	mov	si, word [si]
	add	si, 36
	mov	ax, word [YKCurrTask]
	mov	word [si], ax
L_yakc_39:
	; >>>>> Line:	146
	; >>>>> YKCurrTask->prev = iter->prev; 
	mov	si, word [bp-2]
	add	si, 34
	mov	di, word [YKCurrTask]
	add	di, 34
	mov	ax, word [si]
	mov	word [di], ax
	; >>>>> Line:	147
	; >>>>> iter->prev = YKCurrTask; 
	mov	si, word [bp-2]
	add	si, 34
	mov	ax, word [YKCurrTask]
	mov	word [si], ax
	; >>>>> Line:	149
	; >>>>> if (moved_to_top) 
	mov	ax, word [bp-4]
	test	ax, ax
	je	L_yakc_40
	; >>>>> Line:	150
	; >>>>> YKBlockList = YKCurrTask; 
	mov	ax, word [YKCurrTask]
	mov	word [YKBlockList], ax
L_yakc_40:
L_yakc_35:
	; >>>>> Line:	154
	; >>>>> YKScheduler(); 
	call	YKScheduler
	mov	sp, bp
	pop	bp
	ret
L_yakc_32:
	push	bp
	mov	bp, sp
	sub	sp, 4
	jmp	L_yakc_33
	ALIGN	2
YKEnterISR:
	; >>>>> Line:	157
	; >>>>> void YKEnterISR(void) { 
	jmp	L_yakc_42
L_yakc_43:
	; >>>>> Line:	158
	; >>>>> ++YKISRDepth; 
	inc	word [YKISRDepth]
	mov	sp, bp
	pop	bp
	ret
L_yakc_42:
	push	bp
	mov	bp, sp
	jmp	L_yakc_43
	ALIGN	2
YKExitISR:
	; >>>>> Line:	160
	; >>>>> void YKExitISR(void) { 
	jmp	L_yakc_45
L_yakc_46:
	; >>>>> Line:	161
	; >>>>>  
	dec	word [YKISRDepth]
	; >>>>> Line:	162
	; >>>>> if (YKISRDepth == 0) { 
	mov	ax, word [YKISRDepth]
	test	ax, ax
	jne	L_yakc_47
	; >>>>> Line:	163
	; >>>>> YKScheduler(); 
	call	YKScheduler
L_yakc_47:
	mov	sp, bp
	pop	bp
	ret
L_yakc_45:
	push	bp
	mov	bp, sp
	jmp	L_yakc_46
	ALIGN	2
YKCtxSwCount:
	TIMES	2 db 0
YKIdleCount:
	TIMES	2 db 0
YKTickNum:
	TIMES	2 db 0
YKISRDepth:
	TIMES	2 db 0
YKRunFlag:
	TIMES	2 db 0
YKRdyList:
	TIMES	2 db 0
YKBlockList:
	TIMES	2 db 0
YKAvailTCBList:
	TIMES	2 db 0
YKTCBArray:
	TIMES	190 db 0
YKCurrTask:
	TIMES	2 db 0
YKIdleTaskStack:
	TIMES	512 db 0
