        CPU     8086
        ORG     0h
InterruptVectorTable:
        ; Internal x86 Interrupts:
        dd      0 ; Reserved (Div err)  ; Int 00h
        dd      0 ; Reserved (Step)     ; Int 01h
        dd      0 ; Reserved (NMI)      ; Int 02h
        dd      0 ; Reserved (Break)    ; Int 03h
        dd      0 ; Reserved (Overflow) ; Int 04h
        dd      0                       ; Int 05h
        dd      0                       ; Int 06h
        dd      0                       ; Int 07h
        ; Hardware Interrupts:
        dd      ISRReset ; Reset               ; Int 08h (IRQ 0)
        dd      ISRTick ; Tick                ; Int 09h (IRQ 1)
        dd      ISRKeyboard ; Keyboard            ; Int 0Ah (IRQ 2)
        dd      0 ; Simptris Game Over  ; Int 0Bh (IRQ 3)
        dd      0 ; Simptris New Piece  ; Int 0Ch (IRQ 4)
        dd      0 ; Simptris Received   ; Int 0Dh (IRQ 5)
        dd      0 ; Simptris Touchdown  ; Int 0Eh (IRQ 6)
        dd      0 ; Simptris Clear      ; Int 0Fh (IRQ 7)
        ; Software Interrupts:
        dd      0 ; Reserved (PC BIOS)  ; Int 10h
        dd      0                       ; Int 11h
        dd      0                       ; Int 12h
        dd      0                       ; Int 13h
        dd      0                       ; Int 14h
        dd      0                       ; Int 15h
        dd      0                       ; Int 16h
        dd      0                       ; Int 17h
        dd      0                       ; Int 18h
        dd      0                       ; Int 19h
        dd      0                       ; Int 1Ah
        dd      0                       ; Int 1Bh
        dd      0                       ; Int 1Ch
        dd      0                       ; Int 1Dh
        dd      0                       ; Int 1Eh
        dd      0                       ; Int 1Fh
        dd      0                       ; Int 20h
        dd      0 ; Reserved (DOS)      ; Int 21h
        dd      0 ; Simptris Services   ; Int 22h
        dd      0                       ; Int 23h
        dd      0                       ; Int 24h
        dd      0                       ; Int 25h
        dd      0                       ; Int 26h
        dd      0                       ; Int 27h
        dd      0                       ; Int 28h
        dd      0                       ; Int 29h
        dd      0                       ; Int 2Ah
        dd      0                       ; Int 2Bh
        dd      0                       ; Int 2Ch
        dd      0                       ; Int 2Dh
        dd      0                       ; Int 2Eh
        dd      0                       ; Int 2Fh
KeyBuffer:                              ; Address 0xC0
        dw      0
NewPieceType:                           ; Address 0xC2
        dw      0
NewPieceID:                             ; Address 0xC4
        dw      0
NewPieceOrientation:                    ; Address 0xC6
        dw      0
NewPieceColumn:                         ; Address 0xC8
        dw      0
TouchdownID:                            ; Address 0xCA
	dw	0
ScreenBitMap0:                          ; Address 0xCC
        dw      0
ScreenBitMap1:
        dw      0
ScreenBitMap2:
        dw      0
ScreenBitMap3:
        dw      0
ScreenBitMap4:
        dw      0
ScreenBitMap5:
        dw      0
TIMES   100h-($-$$) db  0               ; Fill up to (but not including) address 100h with 0
	jmp	main
; This file contains support routines for 32-bit on the 8086.
; It is intended for use code generated by the C86 compiler.
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
SR_asldiv:			; l1 /= l2
	push	bp
	mov	bp,sp
	push	bx
	mov	bx,[bp+4]	; Get address of l1	(was push3)
	push	word [bp+8]	; Push hi l2		(was push1)
	push	word [bp+6]	; Push lo l2		(was push2)
	push	word [bx+2]	; Push hi l1
	push	word [bx]	; Push lo l1
	call	SR_ldiv
	mov	bx,[bp+4]	; Restore l1 address
	mov	[bx+2],dx	; Store result
	mov	[bx],ax
	pop	bx
	pop	bp
	ret
SR_aslmod:			; l1 %= l2
	push	bp
	mov	bp,sp
	push	bx
	mov	bx,[bp+4]	; Get address of l1	(was push3)
	push	word [bp+8]	; Push hi l2		(was push1)
	push	word [bp+6]	; Push lo l2		(was push2)
	push	word [bx+2]	; Push hi l1
	push	word [bx]	; Push lo l1
	call	SR_lmod
	mov	bx,[bp+4]	; Restore l1 address
	mov	[bx+2],dx	; Store result
	mov	[bx],ax
	pop	bx
	pop	bp
	ret
SR_aslmul:			; l1 *= l2
	push	bp
	mov	bp,sp
	push	bx
	mov	bx,[bp+4]	; Get address of l1	(was push3)
	push	word [bp+8]	; Push hi l2		(was push1)
	push	word [bp+6]	; Push lo l2		(was push2)
	push	word [bx+2]	; Push hi l1
	push	word [bx]	; Push lo l1
	call	SR_lmul
	add	sp,8
	mov	bx,[bp+4]	; Restore l1 address
	mov	[bx+2],dx	; Store result
	mov	[bx],ax
	pop	bx
	pop	bp
	ret
SR_aslshl:			; l1 <<= l2
	push	bp
	mov	bp,sp
	push	bx
	mov	bx,[bp+4]	; Get address of l1	(was push3)
	push	word [bp+8]	; Push hi l2		(was push1)
	push	word [bp+6]	; Push lo l2		(was push2)
	push	word [bx+2]	; Push hi l1
	push	word [bx]	; Push lo l1
	call	SR_lshl
	add	sp,8
	mov	bx,[bp+4]	; Restore l1 address
	mov	[bx+2],dx	; Store result
	mov	[bx],ax
	pop	bx
	pop	bp
	ret
SR_aslshr:			; l1 >>= l2
	push	bp
	mov	bp,sp
	push	bx
	mov	bx,[bp+4]	; Get address of l1	(was push3)
	push	word [bp+8]	; Push hi l2		(was push1)
	push	word [bp+6]	; Push lo l2		(was push2)
	push	word [bx+2]	; Push hi l1
	push	word [bx]	; Push lo l1
	call	SR_lshr
	add	sp,8
	mov	bx,[bp+4]	; Restore l1 address
	mov	[bx+2],dx	; Store result
	mov	[bx],ax
	pop	bx
	pop	bp
	ret


SR_asuldiv:			; u1 /= u2
	push	bp
	mov	bp,sp
	push	bx
	mov	bx,[bp+4]	; Get address of u1	(was push3)
	push	word [bp+8]	; Push hi u2		(was push1)
	push	word [bp+6]	; Push lo u2		(was push2)
	push	word [bx+2]	; Push hi u1
	push	word [bx]	; Push lo u1
	call	SR_uldiv
	mov	bx,[bp+4]	; Restore u1 address
	mov	[bx+2],dx	; Store result
	mov	[bx],ax
	pop	bx
	pop	bp
	ret
SR_asilmod:			; u1 %= u2
	push	bp
	mov	bp,sp
	push	bx
	mov	bx,[bp+4]	; Get address of u1	(was push3)
	push	word [bp+8]	; Push hi u2		(was push1)
	push	word [bp+6]	; Push lo u2		(was push2)
	push	word [bx+2]	; Push hi u1
	push	word [bx]	; Push lo u1
	call	SR_ilmod
	mov	bx,[bp+4]	; Restore u1 address
	mov	[bx+2],dx	; Store result
	mov	[bx],ax
	pop	bx
	pop	bp
	ret
SR_asulmul:			; u1 *= u2
	push	bp
	mov	bp,sp
	push	bx
	mov	bx,[bp+4]	; Get address of u1	(was push3)
	push	word [bp+8]	; Push hi u2		(was push1)
	push	word [bp+6]	; Push lo u2		(was push2)
	push	word [bx+2]	; Push hi u1
	push	word [bx]	; Push lo u1
	call	SR_ulmul
	add	sp,8
	mov	bx,[bp+4]	; Restore u1 address
	mov	[bx+2],dx	; Store result
	mov	[bx],ax
	pop	bx
	pop	bp
	ret
SR_asulshl:			; u1 << u2
	push	bp
	mov	bp,sp
	push	bx
	mov	bx,[bp+4]	; Get address of u1	(was push3)
	push	word [bp+8]	; Push hi u2		(was push1)
	push	word [bp+6]	; Push lo u2		(was push2)
	push	word [bx+2]	; Push hi u1
	push	word [bx]	; Push lo u1
	call	SR_ulshl
	add	sp,8
	mov	bx,[bp+4]	; Restore u1 address
	mov	[bx+2],dx	; Store result
	mov	[bx],ax
	pop	bx
	pop	bp
	ret
SR_asulshr:			; u1 >> u2
	push	bp
	mov	bp,sp
	push	bx
	mov	bx,[bp+4]	; Get address of u1	(was push3)
	push	word [bp+8]	; Push hi u2		(was push1)
	push	word [bp+6]	; Push lo u2		(was push2)
	push	word [bx+2]	; Push hi u1
	push	word [bx]	; Push lo u1
	call	SR_ulshr
	add	sp,8
	mov	bx,[bp+4]	; Restore u1 address
	mov	[bx+2],dx	; Store result
	mov	[bx],ax
	pop	bx
	pop	bp
	ret


; Main 32-bit routines begin here:

SR_ldiv:	; N_LDIV@
	pop    cx
	push   cs
	push   cx
	; LDIV@
	xor    cx,cx
	jmp    LSR_01
SR_uldiv:	; N_LUDIV@
	pop    cx
	push   cs
	push   cx
	; F_LUDIV@
	mov    cx,0001
	jmp    LSR_01
SR_lmod:	; N_LMOD@
	pop    cx
	push   cs
	push   cx
	; F_LMOD@
	mov    cx,0002
	jmp    LSR_01
SR_ilmod:	; N_LUMOD@
	pop    cx
	push   cs
	push   cx
	; LUMOD@
	mov    cx,0003
LSR_01:
	push   bp
	push   si
	push   di
	mov    bp,sp
	mov    di,cx
	mov    ax,[bp+0Ah]
	mov    dx,[bp+0Ch]
	mov    bx,[bp+0Eh]
	mov    cx,[bp+10h]
	or     cx,cx
	jne    LSR_02
	or     dx,dx
	je     LSR_10
	or     bx,bx
	je     LSR_10
LSR_02:
	test   di,0001
	jne    LSR_04
	or     dx,dx
	jns    LSR_03
	neg    dx
	neg    ax
	sbb    dx,0000
	or     di,000Ch
LSR_03:
	or     cx,cx
	jns    LSR_04
	neg    cx
	neg    bx
	sbb    cx,0000
	xor    di,0004
LSR_04:
	mov    bp,cx
	mov    cx,0020h
	push   di
	xor    di,di
	xor    si,si
LSR_05:
	shl    ax,1
	rcl    dx,1
	rcl    si,1
	rcl    di,1
	cmp    di,bp
	jb     LSR_07
	ja     LSR_06
	cmp    si,bx
	jb     LSR_07
LSR_06:
	sub    si,bx
	sbb    di,bp
	inc    ax
LSR_07:
	loop   LSR_05
	pop    bx
	test   bx,0002
	je     LSR_08
	mov    ax,si
	mov    dx,di
	shr    bx,1
LSR_08:
	test   bx,0004h
	je     LSR_09
	neg    dx
	neg    ax
	sbb    dx,0000
LSR_09:
	pop    di
	pop    si
	pop    bp
	retf   0008
LSR_10:
	div    bx
	test   di,0002
	je     LSR_11
	xchg   dx,ax
LSR_11:
	xor    dx,dx
	jmp    LSR_09
SR_lshl:	; N_LXLSH@
SR_ulshl:
	; r = a << b
	pop    bx
	push   cs
	push   bx

	push   bp
	mov    bp,sp

	push   cx	; C86 doesn't expect use of cx or bx

	mov    ax, [bp+6]	; pop loword(a)
	mov    dx, [bp+8]	; pop hiword(a)
	mov    cx, [bp+10]	; pop word(b)
	
	; LXLSH@
	cmp    cl,10h
	jnb    LSR_12
	mov    bx,ax
	shl    ax,cl
	shl    dx,cl
	neg    cl
	add    cl,10h
	shr    bx,cl
	or     dx,bx
	pop    cx
	pop    bp
	retf
LSR_12:
	sub    cl,10h
	xchg   dx,ax
	xor    ax,ax
	shl    dx,cl
	pop    cx
	pop    bp
	retf
SR_lshr:	; N_LXRSH@
	; r = a >> b
	pop    bx
	push   cs
	push   bx

	push   bp
	mov    bp,sp

	push   cx	; C86 doesn't expect use of cx or bx

        mov    ax, [bp+6]	; pop loword(a)
	mov    dx, [bp+8]	; pop hiword(a)
	mov    cx, [bp+10]	; pop word(b)
	
	; LXRSH@
	cmp    cl,10h
	jnb    LSR_13
	mov    bx,dx
	shr    ax,cl
	sar    dx,cl
	neg    cl
	add    cl,10h
	shl    bx,cl
	or     ax,bx
	pop    cx
	pop    bp
	retf
LSR_13:
	sub    cl,10h
	xchg   dx,ax
	cwd
	sar    ax,cl
	pop    cx
	pop    bp
	retf
SR_ulshr:	; N_LXURSH@
	; r = a >> b
	pop    bx
	push   cs
	push   bx

	push   bp
	mov    bp,sp

	push   cx	; C86 doesn't expect use of cx or bx

        mov    ax, [bp+6]	; pop loword(a)
	mov    dx, [bp+8]	; pop hiword(a)
	mov    cx, [bp+10]	; pop word(b)
	
	; LXURSH@
	cmp    cl,10h
	jnb    LSR_14
	mov    bx,dx
	shr    ax,cl
	shr    dx,cl
	neg    cl
	add    cl,10h
	shl    bx,cl
	or     ax,bx
	pop    cx
	pop    bp
	retf
LSR_14:
	sub    cl,10h
	xchg   dx,ax
	xor    dx,dx
	shr    ax,cl
	pop    cx
	pop    bp
	retf
SR_lmul:	; N_LXMUL@
SR_ulmul:
	; r = a * b
	push   bp
	push   si
	mov    bp,sp

	push   cx	; C86 doesn't expect use of cx or bx
	push   bx

        mov    bx, [bp+6]	; pop loword(a)
	mov    cx, [bp+8]	; pop hiword(a)
	mov    ax, [bp+10]	; pop loword(b)
	mov    dx, [bp+12]	; pop hiword(b)
	
	xchg   si,ax
	xchg   dx,ax
	test   ax,ax
	je     LSR_15
	mul    bx
LSR_15:
	jcxz   LSR_16
	xchg   cx,ax
	mul    si
	add    ax,cx
LSR_16:
	xchg   si,ax
	mul    bx
	add    dx,si
	pop    bx
	pop    cx
	pop    si
	pop    bp
	ret

; Generated by c86 (BYU-NASM) 5.1 (beta) from clib.c
	CPU	8086
	ALIGN	2
	jmp	main	; Jump to program start
new_line:
	db	13,10,36
	ALIGN	2
signalEOI:
	jmp	L_clib_1
L_clib_2:
	mov	al, 0x20
	out	0x20, al
	mov	sp, bp
	pop	bp
	ret
L_clib_1:
	push	bp
	mov	bp, sp
	jmp	L_clib_2
	ALIGN	2
exit:
	jmp	L_clib_4
L_clib_5:
	mov	ah, 4Ch
	mov	al, [bp+4]
	int	21h
	mov	sp, bp
	pop	bp
	ret
L_clib_4:
	push	bp
	mov	bp, sp
	jmp	L_clib_5
	ALIGN	2
print:
	jmp	L_clib_7
L_clib_8:
	mov	ah, 40h
	mov	bx, 1
	mov	cx, [bp+6]
	mov	dx, [bp+4]
	int	21h
	mov	sp, bp
	pop	bp
	ret
L_clib_7:
	push	bp
	mov	bp, sp
	jmp	L_clib_8
	ALIGN	2
printChar:
	jmp	L_clib_10
L_clib_11:
	mov	ah, 2
	mov	dl, [bp+4]
	int	21h
	mov	sp, bp
	pop	bp
	ret
L_clib_10:
	push	bp
	mov	bp, sp
	jmp	L_clib_11
	ALIGN	2
printNewLine:
	jmp	L_clib_13
L_clib_14:
	mov	ah, 9
	mov	dx, new_line
	int	21h
	mov	sp, bp
	pop	bp
	ret
L_clib_13:
	push	bp
	mov	bp, sp
	jmp	L_clib_14
	ALIGN	2
printString:
	jmp	L_clib_16
L_clib_17:
	xor	si,si
	mov	bx, [bp+4]
	jmp	printString2
	printString1:
	inc	si
	printString2:
	cmp	byte [bx+si],0
	jne	printString1
	mov	dx, bx
	mov	cx, si
	mov	ah, 40h
	mov	bx, 1
	int	21h
	mov	sp, bp
	pop	bp
	ret
L_clib_16:
	push	bp
	mov	bp, sp
	push	cx
	jmp	L_clib_17
	ALIGN	2
printInt:
	jmp	L_clib_19
L_clib_20:
	mov	word [bp-2], 0
	mov	word [bp-4], 10000
	cmp	word [bp+4], 0
	jge	L_clib_21
	mov	byte [bp-10], 45
	inc	word [bp-2]
	mov	ax, word [bp+4]
	neg	ax
	mov	word [bp+4], ax
L_clib_21:
	mov	ax, word [bp+4]
	test	ax, ax
	jne	L_clib_22
	mov	word [bp-4], 1
	jmp	L_clib_23
L_clib_22:
	jmp	L_clib_25
L_clib_24:
	mov	ax, word [bp-4]
	cwd
	mov	cx, 10
	idiv	cx
	mov	word [bp-4], ax
L_clib_25:
	mov	ax, word [bp+4]
	cwd
	idiv	word [bp-4]
	test	ax, ax
	je	L_clib_24
L_clib_26:
L_clib_23:
	jmp	L_clib_28
L_clib_27:
	mov	ax, word [bp+4]
	xor	dx, dx
	div	word [bp-4]
	add	al, 48
	mov	si, word [bp-2]
	lea	dx, [bp-10]
	add	si, dx
	mov	byte [si], al
	inc	word [bp-2]
	mov	ax, word [bp+4]
	xor	dx, dx
	div	word [bp-4]
	mov	ax, dx
	mov	word [bp+4], ax
	mov	ax, word [bp-4]
	cwd
	mov	cx, 10
	idiv	cx
	mov	word [bp-4], ax
	mov	ax, word [bp-4]
	mov	word [bp-4], ax
L_clib_28:
	cmp	word [bp-4], 0
	jg	L_clib_27
L_clib_29:
	push	word [bp-2]
	lea	ax, [bp-10]
	push	ax
	call	print
	add	sp, 4
	mov	sp, bp
	pop	bp
	ret
L_clib_19:
	push	bp
	mov	bp, sp
	sub	sp, 10
	jmp	L_clib_20
	ALIGN	2
printLong:
	jmp	L_clib_31
L_clib_32:
	mov	word [bp-2], 0
	mov	word [bp-6], 51712
	mov	word [bp-4], 15258
	cmp	word [bp+6], 0
	jg	L_clib_33
	jl	L_clib_34
	cmp	word [bp+4], 0
	jae	L_clib_33
L_clib_34:
	mov	byte [bp-17], 45
	inc	word [bp-2]
	mov	ax, word [bp+4]
	mov	dx, word [bp+6]
	neg	ax
	adc	dx, 0
	neg	dx
	mov	word [bp+4], ax
	mov	word [bp+6], dx
L_clib_33:
	mov	ax, word [bp+4]
	mov	dx, word [bp+6]
	or	dx, ax
	jne	L_clib_35
	mov	word [bp-6], 1
	mov	word [bp-4], 0
	jmp	L_clib_36
L_clib_35:
	jmp	L_clib_38
L_clib_37:
	mov	ax, 10
	xor	dx, dx
	push	dx
	push	ax
	lea	ax, [bp-6]
	push	ax
	call	SR_asldiv
L_clib_38:
	push	word [bp-4]
	push	word [bp-6]
	push	word [bp+6]
	push	word [bp+4]
	call	SR_ldiv
	or	dx, ax
	je	L_clib_37
L_clib_39:
L_clib_36:
	jmp	L_clib_41
L_clib_40:
	push	word [bp-4]
	push	word [bp-6]
	push	word [bp+6]
	push	word [bp+4]
	call	SR_uldiv
	add	al, 48
	mov	si, word [bp-2]
	lea	dx, [bp-17]
	add	si, dx
	mov	byte [si], al
	inc	word [bp-2]
	push	word [bp-4]
	push	word [bp-6]
	push	word [bp+6]
	push	word [bp+4]
	call	SR_lmod
	mov	word [bp+4], ax
	mov	word [bp+6], dx
	mov	ax, 10
	xor	dx, dx
	push	dx
	push	ax
	lea	ax, [bp-6]
	push	ax
	call	SR_asldiv
L_clib_41:
	cmp	word [bp-4], 0
	jg	L_clib_40
	jne	L_clib_43
	cmp	word [bp-6], 0
	ja	L_clib_40
L_clib_43:
L_clib_42:
	push	word [bp-2]
	lea	ax, [bp-17]
	push	ax
	call	print
	add	sp, 4
	mov	sp, bp
	pop	bp
	ret
L_clib_31:
	push	bp
	mov	bp, sp
	sub	sp, 18
	jmp	L_clib_32
	ALIGN	2
printUInt:
	jmp	L_clib_45
L_clib_46:
	mov	word [bp-2], 0
	mov	word [bp-4], 10000
	mov	ax, word [bp+4]
	test	ax, ax
	jne	L_clib_47
	mov	word [bp-4], 1
	jmp	L_clib_48
L_clib_47:
	jmp	L_clib_50
L_clib_49:
	mov	ax, word [bp-4]
	xor	dx, dx
	mov	cx, 10
	div	cx
	mov	word [bp-4], ax
L_clib_50:
	mov	ax, word [bp+4]
	xor	dx, dx
	div	word [bp-4]
	test	ax, ax
	je	L_clib_49
L_clib_51:
L_clib_48:
	jmp	L_clib_53
L_clib_52:
	mov	ax, word [bp+4]
	xor	dx, dx
	div	word [bp-4]
	add	al, 48
	mov	si, word [bp-2]
	lea	dx, [bp-10]
	add	si, dx
	mov	byte [si], al
	inc	word [bp-2]
	mov	ax, word [bp+4]
	xor	dx, dx
	div	word [bp-4]
	mov	word [bp+4], dx
	mov	ax, word [bp-4]
	xor	dx, dx
	mov	cx, 10
	div	cx
	mov	word [bp-4], ax
L_clib_53:
	mov	ax, word [bp-4]
	test	ax, ax
	jne	L_clib_52
L_clib_54:
	push	word [bp-2]
	lea	ax, [bp-10]
	push	ax
	call	print
	add	sp, 4
	mov	sp, bp
	pop	bp
	ret
L_clib_45:
	push	bp
	mov	bp, sp
	sub	sp, 10
	jmp	L_clib_46
	ALIGN	2
printULong:
	jmp	L_clib_56
L_clib_57:
	mov	word [bp-2], 0
	mov	word [bp-6], 51712
	mov	word [bp-4], 15258
	mov	ax, word [bp+4]
	mov	dx, word [bp+6]
	or	dx, ax
	jne	L_clib_58
	mov	word [bp-6], 1
	mov	word [bp-4], 0
	jmp	L_clib_59
L_clib_58:
	jmp	L_clib_61
L_clib_60:
	mov	ax, 10
	xor	dx, dx
	push	dx
	push	ax
	lea	ax, [bp-6]
	push	ax
	call	SR_asuldiv
L_clib_61:
	push	word [bp-4]
	push	word [bp-6]
	push	word [bp+6]
	push	word [bp+4]
	call	SR_uldiv
	or	dx, ax
	je	L_clib_60
L_clib_62:
L_clib_59:
	jmp	L_clib_64
L_clib_63:
	push	word [bp-4]
	push	word [bp-6]
	push	word [bp+6]
	push	word [bp+4]
	call	SR_uldiv
	add	al, 48
	mov	si, word [bp-2]
	lea	dx, [bp-17]
	add	si, dx
	mov	byte [si], al
	inc	word [bp-2]
	push	word [bp-4]
	push	word [bp-6]
	lea	ax, [bp+4]
	push	ax
	call	SR_asilmod
	mov	ax, 10
	xor	dx, dx
	push	dx
	push	ax
	lea	ax, [bp-6]
	push	ax
	call	SR_asuldiv
L_clib_64:
	mov	ax, word [bp-6]
	mov	dx, word [bp-4]
	or	dx, ax
	jne	L_clib_63
L_clib_65:
	push	word [bp-2]
	lea	ax, [bp-17]
	push	ax
	call	print
	add	sp, 4
	mov	sp, bp
	pop	bp
	ret
L_clib_56:
	push	bp
	mov	bp, sp
	sub	sp, 18
	jmp	L_clib_57
	ALIGN	2
printByte:
	jmp	L_clib_67
L_clib_68:
	mov	al, byte [bp+4]
	cbw
	mov	cx, 4
	sar	ax, cl
	and	ax, 15
	mov	byte [bp-1], al
	cmp	byte [bp-1], 9
	jle	L_clib_69
	mov	al, byte [bp-1]
	cbw
	sub	ax, 10
	add	ax, 65
	jmp	L_clib_70
L_clib_69:
	mov	al, byte [bp-1]
	cbw
	add	ax, 48
L_clib_70:
	mov	byte [bp-3], al
	mov	al, byte [bp+4]
	and	al, 15
	mov	byte [bp-1], al
	cmp	byte [bp-1], 9
	jle	L_clib_71
	mov	al, byte [bp-1]
	cbw
	sub	ax, 10
	add	ax, 65
	jmp	L_clib_72
L_clib_71:
	mov	al, byte [bp-1]
	cbw
	add	ax, 48
L_clib_72:
	mov	byte [bp-2], al
	mov	ax, 2
	push	ax
	lea	ax, [bp-3]
	push	ax
	call	print
	add	sp, 4
	mov	sp, bp
	pop	bp
	ret
L_clib_67:
	push	bp
	mov	bp, sp
	sub	sp, 4
	jmp	L_clib_68
	ALIGN	2
printWord:
	jmp	L_clib_74
L_clib_75:
	mov	word [bp-2], 3
	jmp	L_clib_77
L_clib_76:
	mov	ax, word [bp+4]
	and	ax, 15
	mov	byte [bp-3], al
	cmp	byte [bp-3], 9
	jle	L_clib_80
	mov	al, byte [bp-3]
	cbw
	sub	ax, 10
	add	ax, 65
	jmp	L_clib_81
L_clib_80:
	mov	al, byte [bp-3]
	cbw
	add	ax, 48
L_clib_81:
	mov	si, word [bp-2]
	lea	dx, [bp-7]
	add	si, dx
	mov	byte [si], al
	mov	ax, word [bp+4]
	mov	cx, 4
	sar	ax, cl
	mov	word [bp+4], ax
L_clib_79:
	dec	word [bp-2]
L_clib_77:
	cmp	word [bp-2], 0
	jge	L_clib_76
L_clib_78:
	mov	ax, 4
	push	ax
	lea	ax, [bp-7]
	push	ax
	call	print
	add	sp, 4
	mov	sp, bp
	pop	bp
	ret
L_clib_74:
	push	bp
	mov	bp, sp
	sub	sp, 8
	jmp	L_clib_75
	ALIGN	2
printDWord:
	jmp	L_clib_83
L_clib_84:
	lea	ax, [bp+4]
	mov	si, ax
	mov	ax, word [si]
	mov	word [bp-6], ax
	lea	ax, [bp+4]
	mov	si, ax
	add	si, 2
	mov	ax, word [si]
	mov	word [bp-8], ax
	mov	word [bp-2], 3
	jmp	L_clib_86
L_clib_85:
	mov	ax, word [bp-6]
	and	ax, 15
	mov	byte [bp-3], al
	cmp	byte [bp-3], 9
	jle	L_clib_89
	mov	al, byte [bp-3]
	cbw
	sub	ax, 10
	add	ax, 65
	jmp	L_clib_90
L_clib_89:
	mov	al, byte [bp-3]
	cbw
	add	ax, 48
L_clib_90:
	mov	dx, word [bp-2]
	add	dx, 4
	mov	si, dx
	lea	dx, [bp-16]
	add	si, dx
	mov	byte [si], al
	mov	ax, word [bp-6]
	mov	cx, 4
	sar	ax, cl
	mov	word [bp-6], ax
	mov	ax, word [bp-8]
	and	ax, 15
	mov	byte [bp-3], al
	cmp	byte [bp-3], 9
	jle	L_clib_91
	mov	al, byte [bp-3]
	cbw
	sub	ax, 10
	add	ax, 65
	jmp	L_clib_92
L_clib_91:
	mov	al, byte [bp-3]
	cbw
	add	ax, 48
L_clib_92:
	mov	si, word [bp-2]
	lea	dx, [bp-16]
	add	si, dx
	mov	byte [si], al
	mov	ax, word [bp-8]
	mov	cx, 4
	sar	ax, cl
	mov	word [bp-8], ax
L_clib_88:
	dec	word [bp-2]
L_clib_86:
	cmp	word [bp-2], 0
	jge	L_clib_85
L_clib_87:
	mov	ax, 8
	push	ax
	lea	ax, [bp-16]
	push	ax
	call	print
	add	sp, 4
	mov	sp, bp
	pop	bp
	ret
L_clib_83:
	push	bp
	mov	bp, sp
	sub	sp, 16
	jmp	L_clib_84

; Generated by c86 (BYU-NASM) 5.1 (beta) from myinth.i
	CPU	8086
	ALIGN	2
	jmp	main	; Jump to program start
	ALIGN	2
handleReset:
	; >>>>> Line:	7
	; >>>>> void handleReset() { 
	jmp	L_myinth_1
L_myinth_2:
	; >>>>> Line:	8
	; >>>>> exit(0); 
	xor	al, al
	push	ax
	call	exit
	add	sp, 2
	mov	sp, bp
	pop	bp
	ret
L_myinth_1:
	push	bp
	mov	bp, sp
	jmp	L_myinth_2
L_myinth_4:
	DB	"TICK ",0
	ALIGN	2
handleTick:
	; >>>>> Line:	12
	; >>>>> void handleTick() { 
	jmp	L_myinth_5
L_myinth_6:
	; >>>>> Line:	15
	; >>>>> ++YKTickNum; 
	inc	word [YKTickNum]
	; >>>>> Line:	16
	; >>>>> printNewLine(); 
	call	printNewLine
	; >>>>> Line:	17
	; >>>>> printString("TICK "); 
	mov	ax, L_myinth_4
	push	ax
	call	printString
	add	sp, 2
	; >>>>> Line:	18
	; >>>>> printInt(YKTickNum); 
	push	word [YKTickNum]
	call	printInt
	add	sp, 2
	; >>>>> Line:	20
	; >>>>> current = YKBlockList; 
	mov	ax, word [YKBlockList]
	mov	word [bp-2], ax
	; >>>>> Line:	31
	; >>>>> while ( current ) 
	jmp	L_myinth_8
L_myinth_7:
	; >>>>> Line:	33
	; >>>>> if ( current->state == DELAYED ) 
	mov	si, word [bp-2]
	add	si, 30
	cmp	word [si], 1
	jne	L_myinth_10
	; >>>>> Line:	35
	; >>>>> current->delay--; 
	mov	si, word [bp-2]
	add	si, 32
	dec	word [si]
	; >>>>> Line:	36
	; >>>>> if ( !current->delay ) 
	mov	si, word [bp-2]
	add	si, 32
	mov	ax, word [si]
	test	ax, ax
	jne	L_myinth_11
	; >>>>> Line:	38
	; >>>>> temp = current->prev; 
	mov	si, word [bp-2]
	add	si, 36
	mov	ax, word [si]
	mov	word [bp-4], ax
	; >>>>> Line:	39
	; >>>>> if ( temp ) temp->next = current->next; 
	mov	ax, word [bp-4]
	test	ax, ax
	je	L_myinth_12
	; >>>>> Line:	39
	; >>>>> if ( temp ) temp->next = current->next; 
	mov	si, word [bp-2]
	add	si, 38
	mov	di, word [bp-4]
	add	di, 38
	mov	ax, word [si]
	mov	word [di], ax
	jmp	L_myinth_13
L_myinth_12:
	; >>>>> Line:	40
	; >>>>> else YKBlockList = current->next; 
	mov	si, word [bp-2]
	add	si, 38
	mov	ax, word [si]
	mov	word [YKBlockList], ax
L_myinth_13:
	; >>>>> Line:	42
	; >>>>> temp = current->next; 
	mov	si, word [bp-2]
	add	si, 38
	mov	ax, word [si]
	mov	word [bp-4], ax
	; >>>>> Line:	43
	; >>>>> if ( temp ) temp->prev = current->prev; 
	mov	ax, word [bp-4]
	test	ax, ax
	je	L_myinth_14
	; >>>>> Line:	43
	; >>>>> if ( temp ) temp->prev = current->prev; 
	mov	si, word [bp-2]
	add	si, 36
	mov	di, word [bp-4]
	add	di, 36
	mov	ax, word [si]
	mov	word [di], ax
L_myinth_14:
	; >>>>> Line:	45
	; >>>>> current->prev = 0; 
	mov	si, word [bp-2]
	add	si, 36
	mov	word [si], 0
	; >>>>> Line:	46
	; >>>>> current->next = 0; 
	mov	si, word [bp-2]
	add	si, 38
	mov	word [si], 0
	; >>>>> Line:	47
	; >>>>> current->state = READY; 
	mov	si, word [bp-2]
	add	si, 30
	mov	word [si], 0
	; >>>>> Line:	48
	; >>>>> YKAddReadyTask( current ); 
	push	word [bp-2]
	call	YKAddReadyTask
	add	sp, 2
	; >>>>> Line:	49
	; >>>>> current = temp; 
	mov	ax, word [bp-4]
	mov	word [bp-2], ax
	; >>>>> Line:	50
	; >>>>> continue; 
	jmp	L_myinth_8
L_myinth_11:
L_myinth_10:
	; >>>>> Line:	53
	; >>>>> current = current->next; 
	mov	si, word [bp-2]
	add	si, 38
	mov	ax, word [si]
	mov	word [bp-2], ax
L_myinth_8:
	mov	ax, word [bp-2]
	test	ax, ax
	jne	L_myinth_7
L_myinth_9:
L_myinth_15:
	; >>>>> Line:	57
	; >>>>> return; 
	mov	sp, bp
	pop	bp
	ret
L_myinth_5:
	push	bp
	mov	bp, sp
	sub	sp, 4
	jmp	L_myinth_6
L_myinth_20:
	DB	") IGNORED",0
L_myinth_19:
	DB	"KEYPRESS (",0
L_myinth_18:
	DB	"DELAY COMPLETE",0
L_myinth_17:
	DB	"DELAY KEY PRESSED",0
	ALIGN	2
handleKeyboard:
	; >>>>> Line:	61
	; >>>>> ; 
	jmp	L_myinth_21
L_myinth_22:
	; >>>>> Line:	63
	; >>>>> if (KeyBuffer == 24178) 
	mov	word [bp-2], 0
	; >>>>> Line:	63
	; >>>>> if (KeyBuffer == 24178) 
	cmp	word [KeyBuffer], 24178
	jne	L_myinth_23
	; >>>>> Line:	64
	; >>>>> exit(0); 
	xor	al, al
	push	ax
	call	exit
	add	sp, 2
	jmp	L_myinth_24
L_myinth_23:
	; >>>>> Line:	65
	; >>>>> else if (KeyBuffer == 'd') { 
	cmp	word [KeyBuffer], 100
	jne	L_myinth_25
	; >>>>> Line:	66
	; >>>>> printNewLine(); 
	call	printNewLine
	; >>>>> Line:	67
	; >>>>> printString("DELAY KEY PRESSED"); 
	mov	ax, L_myinth_17
	push	ax
	call	printString
	add	sp, 2
	; >>>>> Line:	68
	; >>>>> for (i = 0; i < 10000; ++i){} 
	mov	word [bp-2], 0
	jmp	L_myinth_27
L_myinth_26:
L_myinth_29:
	; >>>>> Line:	68
	; >>>>> for (i = 0; i < 10000; ++i){} 
	inc	word [bp-2]
L_myinth_27:
	cmp	word [bp-2], 10000
	jl	L_myinth_26
L_myinth_28:
	; >>>>> Line:	69
	; >>>>> printNewLine(); 
	call	printNewLine
	; >>>>> Line:	70
	; >>>>> printString("DELAY COMPLETE"); 
	mov	ax, L_myinth_18
	push	ax
	call	printString
	add	sp, 2
	; >>>>> Line:	71
	; >>>>> printNewLine(); 
	call	printNewLine
	jmp	L_myinth_30
L_myinth_25:
	; >>>>> Line:	73
	; >>>>> else if (KeyBuffer == 24180) { 
	cmp	word [KeyBuffer], 24180
	jne	L_myinth_31
	; >>>>> Line:	74
	; >>>>> handleTick(); 
	call	handleTick
	jmp	L_myinth_32
L_myinth_31:
	; >>>>> Line:	76
	; >>>>> else if (KeyBuffer == 'p') { 
	cmp	word [KeyBuffer], 112
	jne	L_myinth_33
	; >>>>> Line:	77
	; >>>>> YKSemPost(NSemPtr); 
	push	word [NSemPtr]
	call	YKSemPost
	add	sp, 2
	jmp	L_myinth_34
L_myinth_33:
	; >>>>> Line:	80
	; >>>>> printNewLine(); 
	call	printNewLine
	; >>>>> Line:	81
	; >>>>> printString("KEYPRESS ("); 
	mov	ax, L_myinth_19
	push	ax
	call	printString
	add	sp, 2
	; >>>>> Line:	82
	; >>>>>  
	push	word [KeyBuffer]
	call	printChar
	add	sp, 2
	; >>>>> Line:	83
	; >>>>> printString(") IGNORED"); 
	mov	ax, L_myinth_20
	push	ax
	call	printString
	add	sp, 2
	; >>>>> Line:	84
	; >>>>> printNewLine(); 
	call	printNewLine
L_myinth_34:
L_myinth_32:
L_myinth_30:
L_myinth_24:
L_myinth_35:
	; >>>>> Line:	86
	; >>>>> return; 
	mov	sp, bp
	pop	bp
	ret
L_myinth_21:
	push	bp
	mov	bp, sp
	push	cx
	jmp	L_myinth_22
ISRReset:
    ; Save the context of whatever was running by pushing all registers onto the stack,
    ; except SP, SS, CS, IP, and the flags.
    push ax
    push bx
    push cx
    push dx
    push bp
    push si
    push di
    push ds
    push es
	call YKEnterISR
    ; enable interrupts
    sti
    ; call interrupt handler
    call handleReset
    ; disable interrupts
    cli
    ; Signal PIC that handler has finished
    call signalEOI
	call YKExitISR
    ; restore context
    pop es
    pop ds
    pop di
    pop si
    pop bp
    pop dx
    pop cx
    pop bx
    pop ax
    ; return from interrupt
    iret

ISRTick:
    ; Save the context of whatever was running by pushing all registers onto the stack,
    ; except SP, SS, CS, IP, and the flags.
    push ax
    push bx
    push cx
    push dx
    push bp
    push si
    push di
    push ds
    push es
	call YKEnterISR
    ; enable interrupts
    sti
    ; call interrupt handler
    call handleTick
    ; disable interrupts
    cli
    ; Signal PIC that handler has finished
    call signalEOI
	call YKExitISR
    ; restore context
    pop es
    pop ds
    pop di
    pop si
    pop bp
    pop dx
    pop cx
    pop bx
    pop ax
    ; return from interrupt
    iret

ISRKeyboard:
    ; Save the context of whatever was running by pushing all registers onto the stack,
    ; except SP, SS, CS, IP, and the flags.
    push ax
    push bx
    push cx
    push dx
    push bp
    push si
    push di
    push ds
    push es
	call YKEnterISR
    ; enable interrupts
    sti
    ; call interrupt handler
    call handleKeyboard
    ; disable interrupts
    cli
    ; Signal PIC that handler has finished
    call signalEOI
	call YKExitISR
    ; restore context
    pop es
    pop ds
    pop di
    pop si
    pop bp
    pop dx
    pop cx
    pop bx
    pop ax
    ; return from interrupt
    iret




YKDispatcher:
; increment context switch count
    inc word [YKCtxSwCount]
; save context of YKCurrTask
    cli
    push bp
    mov bp, word [YKCurrTask]        ; get tcb block address
    test bp,bp
    je YKDispatcher_1
    mov word [bp],ax                ; save ax
    mov word [bp+2],bx              ; save bx
    mov word [bp+4],cx
    mov word [bp+6],dx
    mov word [bp+14],si             ; save si
    mov si, bp                      ; put tcb block address in si 
    pop bp                          ; restore bp
    mov ax,[bp+2]                   ; get return address
    mov word [si+8],ax              ; save ip
    mov ax,bp                       ; get bp
    add ax,4                        ; get where sp should be
    mov word [si+10],ax             ; save sp
    mov ax,[bp]                     ; get the old bp
    mov word [si+12],ax             ; save bp
    mov word [si+16],di
    mov word [si+18],cs
    mov word [si+20],ss
    mov word [si+22],ds
    mov word [si+24],es
    mov ax,si
    add ax, 28
    mov sp,ax                       ; set sp to get ready to push flags
    pushf                           ; push flags (sp-2 <= flags)
    jmp YKDispatcher_2
YKDispatcher_1:
    pop bp
YKDispatcher_2:
    mov ax, word [YKRdyList]        ; save readylist address
    mov word [YKCurrTask],ax        ; YKCurrTask = YKRdyList
; Restore context of YKRdyList
    ;mov ax, word [YKRdyList]       ; restore ax last
    mov bp, word [YKRdyList]
    mov ax, word [bp]
    mov bx, word [bp+2]
    mov cx, word [bp+4]
    mov dx, word [bp+6]
    ; YKRdyList+8 is ip
    mov sp, word [bp+10]
    mov si, word [bp+14]
    mov di, word [bp+16]
    ;mov cs, word [ax+18] ; this is naughty
    mov ss, word [bp+20]
    mov ds, word [bp+22]
    mov es, word [bp+24]
    push word [bp+26]     ; push flags
    push word [bp+18]     ; push cs
    push word [bp+8]      ; push ip
    mov bp, word [bp+12]
    iret


YKEnterMutex:
    cli
    ret

YKExitMutex:
    sti
    ret
   


; Generated by c86 (BYU-NASM) 5.1 (beta) from yakc.i
	CPU	8086
	ALIGN	2
	jmp	main	; Jump to program start
	ALIGN	2
YKIdleTask:
	; >>>>> Line:	20
	; >>>>> void YKIdleTask(void) { 
	jmp	L_yakc_1
L_yakc_2:
	; >>>>> Line:	22
	; >>>>> while(1){ 
	jmp	L_yakc_4
L_yakc_3:
	; >>>>> Line:	23
	; >>>>> ++dummy; 
	inc	word [bp-2]
	; >>>>> Line:	24
	; >>>>> --dummy; 
	dec	word [bp-2]
	; >>>>> Line:	25
	; >>>>> ++dummy; 
	inc	word [bp-2]
	; >>>>> Line:	26
	; >>>>> ++YKIdleCount; 
	inc	word [YKIdleCount]
L_yakc_4:
	jmp	L_yakc_3
L_yakc_5:
	mov	sp, bp
	pop	bp
	ret
L_yakc_1:
	push	bp
	mov	bp, sp
	push	cx
	jmp	L_yakc_2
	ALIGN	2
YKInitialize:
	; >>>>> Line:	30
	; >>>>> void YKInitialize(void) { 
	jmp	L_yakc_7
L_yakc_8:
	; >>>>> Line:	35
	; >>>>> YKCtxSwCount = 0; 
	mov	word [bp-6], 100
	; >>>>> Line:	35
	; >>>>> YKCtxSwCount = 0; 
	mov	word [YKCtxSwCount], 0
	; >>>>> Line:	36
	; >>>>> YKTickNum = 0; 
	mov	word [YKTickNum], 0
	; >>>>> Line:	37
	; >>>>> YKIdleCount = 0; 
	mov	word [YKIdleCount], 0
	; >>>>> Line:	38
	; >>>>> YKISRDepth = 0; 
	mov	word [YKISRDepth], 0
	; >>>>> Line:	39
	; >>>>> YKRunFlag = 0; 
	mov	word [YKRunFlag], 0
	; >>>>> Line:	40
	; >>>>> YKBlockList = 0; 
	mov	word [YKBlockList], 0
	; >>>>> Line:	41
	; >>>>> YKRdyList = 0; 
	mov	word [YKRdyList], 0
	; >>>>> Line:	42
	; >>>>> cur_t 
	mov	word [YKCurrTask], 0
	; >>>>> Line:	43
	; >>>>> idle_task_p = YKIdleTask; 
	mov	word [bp-2], YKIdleTask
	; >>>>> Line:	44
	; >>>>> idle_task_stack_p = YKIdleTaskStack + 256 - 1; 
	mov	word [bp-4], (YKIdleTaskStack--510)
	; >>>>> Line:	45
	; >>>>> lowest_priority = 100; 
	mov	word [bp-6], 100
	; >>>>> Line:	46
	; >>>>> YKErrorFlag = 0; 
	mov	word [YKErrorFlag], 0
	; >>>>> Line:	49
	; >>>>> YKAvailSEMList = YKSEMArray; 
	mov	word [YKAvailSEMList], YKSEMArray
	; >>>>> Line:	52
	; >>>>> YKAvailTCBList = YKTCBArray; 
	mov	word [YKAvailTCBList], YKTCBArray
	; >>>>> Line:	53
	; >>>>> YKNewTask(idle_task_p, idle_task_stack_p, lowest_priority); 
	push	word [bp-6]
	push	word [bp-4]
	push	word [bp-2]
	call	YKNewTask
	add	sp, 6
	mov	sp, bp
	pop	bp
	ret
L_yakc_7:
	push	bp
	mov	bp, sp
	sub	sp, 6
	jmp	L_yakc_8
	ALIGN	2
YKNewTask:
	; >>>>> Line:	60
	; >>>>> void YKNewTask(void (* task)(void), void *taskStack, unsigned char priority) { 
	jmp	L_yakc_10
L_yakc_11:
	; >>>>> Line:	62
	; >>>>> YKAvailTCBList++; 
	mov	ax, word [YKAvailTCBList]
	mov	word [bp-2], ax
	; >>>>> Line:	62
	; >>>>> YKAvailTCBList++; 
	add	word [YKAvailTCBList], 40
	; >>>>> Line:	63
	; >>>>> cur_tcb->ax = 0; 
	mov	si, word [bp-2]
	mov	word [si], 0
	; >>>>> Line:	64
	; >>>>> cur_tcb->bx = 0; 
	mov	si, word [bp-2]
	add	si, 2
	mov	word [si], 0
	; >>>>> Line:	65
	; >>>>> cur_tcb->cx = 0; 
	mov	si, word [bp-2]
	add	si, 4
	mov	word [si], 0
	; >>>>> Line:	66
	; >>>>> cur_tcb->dx = 0; 
	mov	si, word [bp-2]
	add	si, 6
	mov	word [si], 0
	; >>>>> Line:	67
	; >>>>> print_re 
	mov	si, word [bp-2]
	add	si, 8
	mov	ax, word [bp+4]
	mov	word [si], ax
	; >>>>> Line:	68
	; >>>>> cur_tcb->sp = taskStack; 
	mov	si, word [bp-2]
	add	si, 10
	mov	ax, word [bp+6]
	mov	word [si], ax
	; >>>>> Line:	69
	; >>>>> cur_tcb->bp = taskStack; 
	mov	si, word [bp-2]
	add	si, 12
	mov	ax, word [bp+6]
	mov	word [si], ax
	; >>>>> Line:	70
	; >>>>> cur_tcb->si = 0; 
	mov	si, word [bp-2]
	add	si, 14
	mov	word [si], 0
	; >>>>> Line:	71
	; >>>>> cur_tcb->di = 0; 
	mov	si, word [bp-2]
	add	si, 16
	mov	word [si], 0
	; >>>>> Line:	72
	; >>>>> cur_tcb->cs = 0; 
	mov	si, word [bp-2]
	add	si, 18
	mov	word [si], 0
	; >>>>> Line:	73
	; >>>>> cur_tcb->ss = 0; 
	mov	si, word [bp-2]
	add	si, 20
	mov	word [si], 0
	; >>>>> Line:	74
	; >>>>> cur_tcb->ds = 0; 
	mov	si, word [bp-2]
	add	si, 22
	mov	word [si], 0
	; >>>>> Line:	75
	; >>>>> cur_tcb->es = 0; 
	mov	si, word [bp-2]
	add	si, 24
	mov	word [si], 0
	; >>>>> Line:	76
	; >>>>> cur_tcb->flags = 512; 
	mov	si, word [bp-2]
	add	si, 26
	mov	word [si], 512
	; >>>>> Line:	77
	; >>>>> cur_tcb->priority = priority; 
	mov	al, byte [bp+8]
	xor	ah, ah
	mov	si, word [bp-2]
	add	si, 28
	mov	word [si], ax
	; >>>>> Line:	78
	; >>>>> cur_tcb->state = READY; 
	mov	si, word [bp-2]
	add	si, 30
	mov	word [si], 0
	; >>>>> Line:	79
	; >>>>> cur_tcb->delay = 0; 
	mov	si, word [bp-2]
	add	si, 32
	mov	word [si], 0
	; >>>>> Line:	80
	; >>>>> cur_tcb->prev = 0; 
	mov	si, word [bp-2]
	add	si, 36
	mov	word [si], 0
	; >>>>> Line:	81
	; >>>>> cur_tcb->next = 0; 
	mov	si, word [bp-2]
	add	si, 38
	mov	word [si], 0
	; >>>>> Line:	82
	; >>>>> YKAddReadyTask(cur_tcb); 
	push	word [bp-2]
	call	YKAddReadyTask
	add	sp, 2
	; >>>>> Line:	84
	; >>>>> if (YKRunFlag) { 
	mov	ax, word [YKRunFlag]
	test	ax, ax
	je	L_yakc_12
	; >>>>> Line:	85
	; >>>>> YKScheduler(); 
	call	YKScheduler
L_yakc_12:
	mov	sp, bp
	pop	bp
	ret
L_yakc_10:
	push	bp
	mov	bp, sp
	push	cx
	jmp	L_yakc_11
	ALIGN	2
YKRun:
	; >>>>> Line:	89
	; >>>>> void YKRun(void) { 
	jmp	L_yakc_14
L_yakc_15:
	; >>>>> Line:	90
	; >>>>> YKRunFlag = 1; 
	mov	word [YKRunFlag], 1
	; >>>>> Line:	91
	; >>>>> YKScheduler(); 
	call	YKScheduler
	mov	sp, bp
	pop	bp
	ret
L_yakc_14:
	push	bp
	mov	bp, sp
	jmp	L_yakc_15
	ALIGN	2
print_ready_list:
	; >>>>> Line:	95
	; >>>>> { 
	jmp	L_yakc_17
L_yakc_18:
	; >>>>> Line:	98
	; >>>>> while( iter ) 
	mov	word [bp-2], 0
	mov	ax, word [YKRdyList]
	mov	word [bp-4], ax
	; >>>>> Line:	98
	; >>>>> while( iter ) 
	jmp	L_yakc_20
L_yakc_19:
	; >>>>> Line:	100
	; >>>>> printInt( iter->priority ); 
	mov	si, word [bp-4]
	add	si, 28
	push	word [si]
	call	printInt
	add	sp, 2
	; >>>>> Line:	101
	; >>>>> printNewLine(); 
	call	printNewLine
	; >>>>> Line:	102
	; >>>>> iter = iter->next; 
	mov	si, word [bp-4]
	add	si, 38
	mov	ax, word [si]
	mov	word [bp-4], ax
	; >>>>> Line:	103
	; >>>>> ++count; 
	inc	word [bp-2]
L_yakc_20:
	mov	ax, word [bp-4]
	test	ax, ax
	jne	L_yakc_19
L_yakc_21:
	; >>>>> Line:	105
	; >>>>> return count; 
	mov	ax, word [bp-2]
L_yakc_22:
	mov	sp, bp
	pop	bp
	ret
L_yakc_17:
	push	bp
	mov	bp, sp
	sub	sp, 4
	jmp	L_yakc_18
L_yakc_25:
	DB	" Semaphore: ",0
L_yakc_24:
	DB	" Delay: ",0
	ALIGN	2
print_delay_list:
	; >>>>> Line:	109
	; >>>>> { 
	jmp	L_yakc_26
L_yakc_27:
	; >>>>> Line:	112
	; >>>>> while( iter ) 
	mov	word [bp-2], 0
	mov	ax, word [YKBlockList]
	mov	word [bp-4], ax
	; >>>>> Line:	112
	; >>>>> while( iter ) 
	jmp	L_yakc_29
L_yakc_28:
	; >>>>> Line:	114
	; >>>>> printInt( iter->priority ); 
	mov	si, word [bp-4]
	add	si, 28
	push	word [si]
	call	printInt
	add	sp, 2
	; >>>>> Line:	115
	; >>>>> if (iter->state == DELAYED) { 
	mov	si, word [bp-4]
	add	si, 30
	cmp	word [si], 1
	jne	L_yakc_31
	; >>>>> Line:	116
	; >>>>> printString( " Delay: " ); 
	mov	ax, L_yakc_24
	push	ax
	call	printString
	add	sp, 2
	; >>>>> Line:	117
	; >>>>> printInt( iter->delay ); 
	mov	si, word [bp-4]
	add	si, 32
	push	word [si]
	call	printInt
	add	sp, 2
	jmp	L_yakc_32
L_yakc_31:
	; >>>>> Line:	119
	; >>>>> else if (iter->state == SEMAPHORE) { 
	mov	si, word [bp-4]
	add	si, 30
	cmp	word [si], 2
	jne	L_yakc_33
	; >>>>> Line:	120
	; >>>>> printString( " Semaphore: " ); 
	mov	ax, L_yakc_25
	push	ax
	call	printString
	add	sp, 2
	; >>>>> Line:	121
	; >>>>>  
	mov	si, word [bp-4]
	add	si, 34
	mov	si, word [si]
	push	word [si]
	call	printInt
	add	sp, 2
L_yakc_33:
L_yakc_32:
	; >>>>> Line:	123
	; >>>>> printNewLine(); 
	call	printNewLine
	; >>>>> Line:	124
	; >>>>> iter = iter->next; 
	mov	si, word [bp-4]
	add	si, 38
	mov	ax, word [si]
	mov	word [bp-4], ax
	; >>>>> Line:	125
	; >>>>> ++count; 
	inc	word [bp-2]
L_yakc_29:
	mov	ax, word [bp-4]
	test	ax, ax
	jne	L_yakc_28
L_yakc_30:
	; >>>>> Line:	127
	; >>>>> return count; 
	mov	ax, word [bp-2]
L_yakc_34:
	mov	sp, bp
	pop	bp
	ret
L_yakc_26:
	push	bp
	mov	bp, sp
	sub	sp, 4
	jmp	L_yakc_27
	ALIGN	2
YKScheduler:
	; >>>>> Line:	130
	; >>>>> void YKScheduler(void) { 
	jmp	L_yakc_36
L_yakc_37:
	; >>>>> Line:	131
	; >>>>> if (YKCurrTask != YKRdyList) { 
	mov	ax, word [YKRdyList]
	cmp	ax, word [YKCurrTask]
	je	L_yakc_38
	; >>>>> Line:	152
	; >>>>> YKDispatcher(); 
	call	YKDispatcher
L_yakc_38:
	mov	sp, bp
	pop	bp
	ret
L_yakc_36:
	push	bp
	mov	bp, sp
	jmp	L_yakc_37
	ALIGN	2
YKAddReadyTask:
	; >>>>> Line:	157
	; >>>>> void YKAddReadyTask(tcb_t *cur_tcb) { 
	jmp	L_yakc_40
L_yakc_41:
	; >>>>> Line:	160
	; >>>>> if(YKRdyList == 0) { 
	mov	ax, word [YKRdyList]
	test	ax, ax
	jne	L_yakc_42
	; >>>>> Line:	161
	; >>>>> YKRdyList = cur_tcb; 
	mov	ax, word [bp+4]
	mov	word [YKRdyList], ax
	jmp	L_yakc_43
L_yakc_42:
	; >>>>> Line:	164
	; >>>>> iter = YKRdyList; 
	mov	ax, word [YKRdyList]
	mov	word [bp-4], ax
	; >>>>> Line:	165
	; >>>>> moved_to_top = 1; 
	mov	word [bp-2], 1
	; >>>>> Line:	166
	; >>>>> while (cur_tcb->priority > iter->priority) { 
	jmp	L_yakc_45
L_yakc_44:
	; >>>>> Line:	167
	; >>>>> iter = ite 
	mov	si, word [bp-4]
	add	si, 38
	mov	ax, word [si]
	mov	word [bp-4], ax
	; >>>>> Line:	168
	; >>>>> moved_to_top = 0; 
	mov	word [bp-2], 0
L_yakc_45:
	mov	si, word [bp+4]
	add	si, 28
	mov	di, word [bp-4]
	add	di, 28
	mov	ax, word [di]
	cmp	ax, word [si]
	jl	L_yakc_44
L_yakc_46:
	; >>>>> Line:	170
	; >>>>> cur_tcb->next = iter; 
	mov	si, word [bp+4]
	add	si, 38
	mov	ax, word [bp-4]
	mov	word [si], ax
	; >>>>> Line:	171
	; >>>>> if (iter->prev) 
	mov	si, word [bp-4]
	add	si, 36
	mov	ax, word [si]
	test	ax, ax
	je	L_yakc_47
	; >>>>> Line:	172
	; >>>>> iter->prev->next = cur_tcb; 
	mov	si, word [bp-4]
	add	si, 36
	mov	si, word [si]
	add	si, 38
	mov	ax, word [bp+4]
	mov	word [si], ax
L_yakc_47:
	; >>>>> Line:	174
	; >>>>> cur_tcb->prev = iter->prev; 
	mov	si, word [bp-4]
	add	si, 36
	mov	di, word [bp+4]
	add	di, 36
	mov	ax, word [si]
	mov	word [di], ax
	; >>>>> Line:	175
	; >>>>> iter->prev = cur_tcb; 
	mov	si, word [bp-4]
	add	si, 36
	mov	ax, word [bp+4]
	mov	word [si], ax
	; >>>>> Line:	177
	; >>>>> if (moved_to_top) 
	mov	ax, word [bp-2]
	test	ax, ax
	je	L_yakc_48
	; >>>>> Line:	178
	; >>>>> YKRdyList = cur_tcb; 
	mov	ax, word [bp+4]
	mov	word [YKRdyList], ax
L_yakc_48:
L_yakc_43:
L_yakc_49:
	; >>>>> Line:	180
	; >>>>> return; 
	mov	sp, bp
	pop	bp
	ret
L_yakc_40:
	push	bp
	mov	bp, sp
	sub	sp, 4
	jmp	L_yakc_41
	ALIGN	2
YKBlockTask:
	; >>>>> Line:	183
	; >>>>> void YKBlockTask(){ 
	jmp	L_yakc_51
L_yakc_52:
	; >>>>> Line:	185
	; >>>>> YKRdyList = YKCurrTask->next; 
	mov	si, word [YKCurrTask]
	add	si, 38
	mov	ax, word [si]
	mov	word [YKRdyList], ax
	; >>>>> Line:	186
	; >>>>> YKRdyList->prev = 0; 
	mov	si, word [YKRdyList]
	add	si, 36
	mov	word [si], 0
	; >>>>> Line:	189
	; >>>>> if (YKBlockList == 0) { 
	mov	ax, word [YKBlockList]
	test	ax, ax
	jne	L_yakc_53
	; >>>>> Line:	190
	; >>>>> YKBlockList = YKCurrTask; 
	mov	ax, word [YKCurrTask]
	mov	word [YKBlockList], ax
	; >>>>> Line:	191
	; >>>>> YKBlockList->next = 0; 
	mov	si, word [YKBlockList]
	add	si, 38
	mov	word [si], 0
	jmp	L_yakc_54
L_yakc_53:
	; >>>>> Line:	193
	; >>>>> else if ( YKBlockList->priority > YKCurrTa 
	mov	si, word [YKBlockList]
	add	si, 28
	mov	di, word [YKCurrTask]
	add	di, 28
	mov	ax, word [di]
	cmp	ax, word [si]
	jge	L_yakc_55
	; >>>>> Line:	195
	; >>>>> YKCurrTask->next = YKBlockList; 
	mov	si, word [YKCurrTask]
	add	si, 38
	mov	ax, word [YKBlockList]
	mov	word [si], ax
	; >>>>> Line:	196
	; >>>>> YKBlockList->prev = YKCurrTask; 
	mov	si, word [YKBlockList]
	add	si, 36
	mov	ax, word [YKCurrTask]
	mov	word [si], ax
	; >>>>> Line:	197
	; >>>>> YKCurrTask->prev = 0; 
	mov	si, word [YKCurrTask]
	add	si, 36
	mov	word [si], 0
	; >>>>> Line:	198
	; >>>>> YKBlockList = YKCurrTask; 
	mov	ax, word [YKCurrTask]
	mov	word [YKBlockList], ax
	jmp	L_yakc_56
L_yakc_55:
	; >>>>> Line:	203
	; >>>>> while ( iter->next && YKCurrTask->priority > iter->next->priority ) { 
	mov	ax, word [YKBlockList]
	mov	word [bp-2], ax
	; >>>>> Line:	203
	; >>>>> while ( iter->next && YKCurrTask->priority > iter->next->priority ) { 
	jmp	L_yakc_58
L_yakc_57:
	; >>>>> Line:	204
	; >>>>> iter = iter->next; 
	mov	si, word [bp-2]
	add	si, 38
	mov	ax, word [si]
	mov	word [bp-2], ax
L_yakc_58:
	mov	si, word [bp-2]
	add	si, 38
	mov	ax, word [si]
	test	ax, ax
	je	L_yakc_60
	mov	si, word [bp-2]
	add	si, 38
	mov	si, word [si]
	add	si, 28
	mov	di, word [YKCurrTask]
	add	di, 28
	mov	ax, word [di]
	cmp	ax, word [si]
	jg	L_yakc_57
L_yakc_60:
L_yakc_59:
	; >>>>> Line:	207
	; >>>>> YKCurrTask->next = iter->next; 
	mov	si, word [bp-2]
	add	si, 38
	mov	di, word [YKCurrTask]
	add	di, 38
	mov	ax, word [si]
	mov	word [di], ax
	; >>>>> Line:	208
	; >>>>> if (iter->next) 
	mov	si, word [bp-2]
	add	si, 38
	mov	ax, word [si]
	test	ax, ax
	je	L_yakc_61
	; >>>>> Line:	209
	; >>>>> iter->next->prev = YKCurrTask; 
	mov	si, word [bp-2]
	add	si, 38
	mov	si, word [si]
	add	si, 36
	mov	ax, word [YKCurrTask]
	mov	word [si], ax
L_yakc_61:
	; >>>>> Line:	211
	; >>>>> YKCurrTask->prev = iter; 
	mov	si, word [YKCurrTask]
	add	si, 36
	mov	ax, word [bp-2]
	mov	word [si], ax
	; >>>>> Line:	212
	; >>>>> iter->next = YKCurrTask; 
	mov	si, word [bp-2]
	add	si, 38
	mov	ax, word [YKCurrTask]
	mov	word [si], ax
L_yakc_56:
L_yakc_54:
	mov	sp, bp
	pop	bp
	ret
L_yakc_51:
	push	bp
	mov	bp, sp
	push	cx
	jmp	L_yakc_52
	ALIGN	2
YKBlock2Ready:
	; >>>>> Line:	216
	; >>>>> dy(YKSEM* semapho 
	jmp	L_yakc_63
L_yakc_64:
	; >>>>> Line:	219
	; >>>>> current = YKBlockList; 
	mov	ax, word [YKBlockList]
	mov	word [bp-2], ax
	; >>>>> Line:	221
	; >>>>> while ( current ) 
	jmp	L_yakc_66
L_yakc_65:
	; >>>>> Line:	223
	; >>>>> if ( current == task ) 
	mov	ax, word [bp+4]
	cmp	ax, word [bp-2]
	jne	L_yakc_68
	; >>>>> Line:	225
	; >>>>> temp = current->prev; 
	mov	si, word [bp-2]
	add	si, 36
	mov	ax, word [si]
	mov	word [bp-4], ax
	; >>>>> Line:	226
	; >>>>> if ( temp ) temp->next = current->next; 
	mov	ax, word [bp-4]
	test	ax, ax
	je	L_yakc_69
	; >>>>> Line:	226
	; >>>>> if ( temp ) temp->next = current->next; 
	mov	si, word [bp-2]
	add	si, 38
	mov	di, word [bp-4]
	add	di, 38
	mov	ax, word [si]
	mov	word [di], ax
	jmp	L_yakc_70
L_yakc_69:
	; >>>>> Line:	227
	; >>>>> else YKBlockList = current->next; 
	mov	si, word [bp-2]
	add	si, 38
	mov	ax, word [si]
	mov	word [YKBlockList], ax
L_yakc_70:
	; >>>>> Line:	229
	; >>>>> temp = current->next; 
	mov	si, word [bp-2]
	add	si, 38
	mov	ax, word [si]
	mov	word [bp-4], ax
	; >>>>> Line:	230
	; >>>>> if ( temp ) temp->prev = current->prev; 
	mov	ax, word [bp-4]
	test	ax, ax
	je	L_yakc_71
	; >>>>> Line:	230
	; >>>>> if ( temp ) temp->prev = current->prev; 
	mov	si, word [bp-2]
	add	si, 36
	mov	di, word [bp-4]
	add	di, 36
	mov	ax, word [si]
	mov	word [di], ax
L_yakc_71:
	; >>>>> Line:	232
	; >>>>> current->prev = 0; 
	mov	si, word [bp-2]
	add	si, 36
	mov	word [si], 0
	; >>>>> Line:	233
	; >>>>> current->next = 0; 
	mov	si, word [bp-2]
	add	si, 38
	mov	word [si], 0
	; >>>>> Line:	234
	; >>>>> current->state = READY; 
	mov	si, word [bp-2]
	add	si, 30
	mov	word [si], 0
	; >>>>> Line:	235
	; >>>>> YKAddReadyTask( current ); 
	push	word [bp-2]
	call	YKAddReadyTask
	add	sp, 2
	; >>>>> Line:	236
	; >>>>> current = temp; 
	mov	ax, word [bp-4]
	mov	word [bp-2], ax
	; >>>>> Line:	237
	; >>>>> continue; 
	jmp	L_yakc_66
L_yakc_68:
	; >>>>> Line:	240
	; >>>>> current = current->next; 
	mov	si, word [bp-2]
	add	si, 38
	mov	ax, word [si]
	mov	word [bp-2], ax
L_yakc_66:
	mov	ax, word [bp-2]
	test	ax, ax
	jne	L_yakc_65
L_yakc_67:
L_yakc_72:
	; >>>>> Line:	242
	; >>>>> return; 
	mov	sp, bp
	pop	bp
	ret
L_yakc_63:
	push	bp
	mov	bp, sp
	sub	sp, 4
	jmp	L_yakc_64
	ALIGN	2
YKBlockSEM2Ready:
	; >>>>> Line:	245
	; >>>>> ; 
	jmp	L_yakc_74
L_yakc_75:
	; >>>>> Line:	248
	; >>>>> current = YKBlockList; 
	mov	ax, word [YKBlockList]
	mov	word [bp-2], ax
	; >>>>> Line:	250
	; >>>>> while ( current ) 
	jmp	L_yakc_77
L_yakc_76:
	; >>>>> Line:	252
	; >>>>> if ( current->semaphore == semaphore ) 
	mov	si, word [bp-2]
	add	si, 34
	mov	ax, word [bp+4]
	cmp	ax, word [si]
	jne	L_yakc_79
	; >>>>> Line:	254
	; >>>>> temp = current->prev; 
	mov	si, word [bp-2]
	add	si, 36
	mov	ax, word [si]
	mov	word [bp-4], ax
	; >>>>> Line:	255
	; >>>>> if ( temp ) temp->next = current->next; 
	mov	ax, word [bp-4]
	test	ax, ax
	je	L_yakc_80
	; >>>>> Line:	255
	; >>>>> if ( temp ) temp->next = current->next; 
	mov	si, word [bp-2]
	add	si, 38
	mov	di, word [bp-4]
	add	di, 38
	mov	ax, word [si]
	mov	word [di], ax
	jmp	L_yakc_81
L_yakc_80:
	; >>>>> Line:	256
	; >>>>> else YKBlockList = current->next; 
	mov	si, word [bp-2]
	add	si, 38
	mov	ax, word [si]
	mov	word [YKBlockList], ax
L_yakc_81:
	; >>>>> Line:	258
	; >>>>> temp = current->next; 
	mov	si, word [bp-2]
	add	si, 38
	mov	ax, word [si]
	mov	word [bp-4], ax
	; >>>>> Line:	259
	; >>>>> if ( temp ) temp->prev = current->prev; 
	mov	ax, word [bp-4]
	test	ax, ax
	je	L_yakc_82
	; >>>>> Line:	259
	; >>>>> if ( temp ) temp->prev = current->prev; 
	mov	si, word [bp-2]
	add	si, 36
	mov	di, word [bp-4]
	add	di, 36
	mov	ax, word [si]
	mov	word [di], ax
L_yakc_82:
	; >>>>> Line:	261
	; >>>>> current->prev = 0; 
	mov	si, word [bp-2]
	add	si, 36
	mov	word [si], 0
	; >>>>> Line:	262
	; >>>>> current->next = 0; 
	mov	si, word [bp-2]
	add	si, 38
	mov	word [si], 0
	; >>>>> Line:	263
	; >>>>> current->state = READY; 
	mov	si, word [bp-2]
	add	si, 30
	mov	word [si], 0
	; >>>>> Line:	264
	; >>>>> YKAddReadyTask( current ); 
	push	word [bp-2]
	call	YKAddReadyTask
	add	sp, 2
	; >>>>> Line:	265
	; >>>>> current = temp; 
	mov	ax, word [bp-4]
	mov	word [bp-2], ax
	; >>>>> Line:	266
	; >>>>> continue; 
	jmp	L_yakc_77
L_yakc_79:
	; >>>>> Line:	269
	; >>>>> current = current->next; 
	mov	si, word [bp-2]
	add	si, 38
	mov	ax, word [si]
	mov	word [bp-2], ax
L_yakc_77:
	mov	ax, word [bp-2]
	test	ax, ax
	jne	L_yakc_76
L_yakc_78:
L_yakc_83:
	; >>>>> Line:	271
	; >>>>> return; 
	mov	sp, bp
	pop	bp
	ret
L_yakc_74:
	push	bp
	mov	bp, sp
	sub	sp, 4
	jmp	L_yakc_75
	ALIGN	2
YKDelayTask:
	; >>>>> Line:	274
	; >>>>>  
	jmp	L_yakc_85
L_yakc_86:
	; >>>>> Line:	276
	; >>>>> YKCurrTask->delay = count; 
	mov	si, word [YKCurrTask]
	add	si, 32
	mov	ax, word [bp+4]
	mov	word [si], ax
	; >>>>> Line:	277
	; >>>>> YKCurrTask->state = DELAYED; 
	mov	si, word [YKCurrTask]
	add	si, 30
	mov	word [si], 1
	; >>>>> Line:	280
	; >>>>> YKEnterMutex(); 
	call	YKEnterMutex
	; >>>>> Line:	281
	; >>>>> YKBlockTask(); 
	call	YKBlockTask
	; >>>>> Line:	282
	; >>>>> YKExitMutex(); 
	call	YKExitMutex
	; >>>>> Line:	285
	; >>>>> YKScheduler(); 
	call	YKScheduler
	mov	sp, bp
	pop	bp
	ret
L_yakc_85:
	push	bp
	mov	bp, sp
	jmp	L_yakc_86
	ALIGN	2
YKEnterISR:
	; >>>>> Line:	288
	; >>>>> void YKEnterISR(void) { 
	jmp	L_yakc_88
L_yakc_89:
	; >>>>> Line:	289
	; >>>>> ++YKISRDepth; 
	inc	word [YKISRDepth]
	mov	sp, bp
	pop	bp
	ret
L_yakc_88:
	push	bp
	mov	bp, sp
	jmp	L_yakc_89
	ALIGN	2
YKExitISR:
	; >>>>> Line:	291
	; >>>>> void YKExitISR(void) { 
	jmp	L_yakc_91
L_yakc_92:
	; >>>>> Line:	292
	; >>>>> --YKISRDepth; 
	dec	word [YKISRDepth]
	; >>>>> Line:	297
	; >>>>> if (YKISRDepth == 0) { 
	mov	ax, word [YKISRDepth]
	test	ax, ax
	jne	L_yakc_93
	; >>>>> Line:	298
	; >>>>> YKScheduler(); 
	call	YKScheduler
L_yakc_93:
	mov	sp, bp
	pop	bp
	ret
L_yakc_91:
	push	bp
	mov	bp, sp
	jmp	L_yakc_92
	ALIGN	2
YKSemCreate:
	; >>>>> Line:	302
	; >>>>> YKSEM* YKSemCreate(int initialValue) { 
	jmp	L_yakc_95
L_yakc_96:
	; >>>>> Line:	304
	; >>>>> YKAvailSEMList->value = initialValue; 
	mov	si, word [YKAvailSEMList]
	mov	ax, word [bp+4]
	mov	word [si], ax
	; >>>>> Line:	305
	; >>>>> return_val = YKAvailSEMList; 
	mov	ax, word [YKAvailSEMList]
	mov	word [bp-2], ax
	; >>>>> Line:	306
	; >>>>> ++YKAvailSEMList; 
	add	word [YKAvailSEMList], 2
	; >>>>> Line:	307
	; >>>>> return return_val; 
	mov	ax, word [bp-2]
L_yakc_97:
	mov	sp, bp
	pop	bp
	ret
L_yakc_95:
	push	bp
	mov	bp, sp
	push	cx
	jmp	L_yakc_96
	ALIGN	2
YKSemPend:
	; >>>>> Line:	310
	; >>>>> YKBlockSE 
	jmp	L_yakc_99
L_yakc_100:
	; >>>>> Line:	312
	; >>>>> YKEnterMutex(); 
	call	YKEnterMutex
	; >>>>> Line:	315
	; >>>>> available = semaphore->value > 0 ? 1 : 0; 
	mov	si, word [bp+4]
	cmp	word [si], 0
	jle	L_yakc_101
	mov	ax, 1
	jmp	L_yakc_102
L_yakc_101:
	xor	ax, ax
L_yakc_102:
	mov	word [bp-2], ax
	; >>>>> Line:	316
	; >>>>> --(semaphore->value); 
	mov	si, word [bp+4]
	dec	word [si]
	; >>>>> Line:	319
	; >>>>> if (!available) { 
	mov	ax, word [bp-2]
	test	ax, ax
	jne	L_yakc_103
	; >>>>> Line:	320
	; >>>>> YKCurrTask->state = SEMAPHORE; 
	mov	si, word [YKCurrTask]
	add	si, 30
	mov	word [si], 2
	; >>>>> Line:	321
	; >>>>> YKCurrTask->semaphore = semaphore; 
	mov	si, word [YKCurrTask]
	add	si, 34
	mov	ax, word [bp+4]
	mov	word [si], ax
	; >>>>> Line:	322
	; >>>>> YKBlockTask(YKCurrTask); 
	push	word [YKCurrTask]
	call	YKBlockTask
	add	sp, 2
L_yakc_103:
	; >>>>> Line:	325
	; >>>>> YKExitMutex(); 
	call	YKExitMutex
	; >>>>> Line:	329
	; >>>>> YKScheduler(); 
	call	YKScheduler
	mov	sp, bp
	pop	bp
	ret
L_yakc_99:
	push	bp
	mov	bp, sp
	push	cx
	jmp	L_yakc_100
	ALIGN	2
YKSemPost:
	; >>>>> Line:	332
	; >>>>> void YKSemPost(YKSEM *semaphore) { 
	jmp	L_yakc_105
L_yakc_106:
	; >>>>> Line:	333
	; >>>>> YKEnterMutex(); 
	call	YKEnterMutex
	; >>>>> Line:	334
	; >>>>> ++(semaphore->value); 
	mov	si, word [bp+4]
	inc	word [si]
	; >>>>> Line:	335
	; >>>>> if (semaphore->value > 1) 
	mov	si, word [bp+4]
	cmp	word [si], 1
	jle	L_yakc_107
	; >>>>> Line:	336
	; >>>>> semaphore->value = 1; 
	mov	word [si], 1
L_yakc_107:
	; >>>>> Line:	338
	; >>>>> if (semaphore->value < 1) { 
	mov	si, word [bp+4]
	cmp	word [si], 1
	jge	L_yakc_108
	; >>>>> Line:	339
	; >>>>> YKBlockSE 
	push	word [bp+4]
	call	YKBlockSEM2Ready
	add	sp, 2
L_yakc_108:
	; >>>>> Line:	343
	; >>>>> if (YKISRDepth == 0) 
	mov	ax, word [YKISRDepth]
	test	ax, ax
	jne	L_yakc_109
	; >>>>> Line:	344
	; >>>>> YKScheduler(); 
	call	YKScheduler
L_yakc_109:
	; >>>>> Line:	345
	; >>>>> YKExitMutex(); 
	call	YKExitMutex
	mov	sp, bp
	pop	bp
	ret
L_yakc_105:
	push	bp
	mov	bp, sp
	jmp	L_yakc_106
	ALIGN	2
YKCtxSwCount:
	TIMES	2 db 0
YKIdleCount:
	TIMES	2 db 0
YKTickNum:
	TIMES	2 db 0
YKISRDepth:
	TIMES	2 db 0
YKRunFlag:
	TIMES	2 db 0
YKRdyList:
	TIMES	2 db 0
YKBlockList:
	TIMES	2 db 0
YKAvailTCBList:
	TIMES	2 db 0
YKTCBArray:
	TIMES	240 db 0
YKCurrTask:
	TIMES	2 db 0
YKIdleTaskStack:
	TIMES	512 db 0
YKErrorFlag:
	TIMES	2 db 0
YKSEMArray:
	TIMES	8 db 0
YKAvailSEMList:
	TIMES	2 db 0
; Generated by c86 (BYU-NASM) 5.1 (beta) from lab5app.i
	CPU	8086
	ALIGN	2
	jmp	main	; Jump to program start
L_lab5app_3:
	DB	"works",0
L_lab5app_2:
	DB	"it",0
L_lab5app_1:
	DB	"Hey",0
	ALIGN	2
TaskWord:
	; >>>>> Line:	24
	; >>>>> { 
	jmp	L_lab5app_4
L_lab5app_5:
	; >>>>> Line:	25
	; >>>>> while (1) 
	jmp	L_lab5app_7
L_lab5app_6:
	; >>>>> Line:	27
	; >>>>> YKSemPend(WSemPtr); 
	push	word [WSemPtr]
	call	YKSemPend
	add	sp, 2
	; >>>>> Line:	28
	; >>>>>  
	mov	ax, L_lab5app_1
	push	ax
	call	printString
	add	sp, 2
	; >>>>> Line:	29
	; >>>>> YKSemPost(PSemPtr); 
	push	word [PSemPtr]
	call	YKSemPost
	add	sp, 2
	; >>>>> Line:	31
	; >>>>> YKSemPend(WSemPtr); 
	push	word [WSemPtr]
	call	YKSemPend
	add	sp, 2
	; >>>>> Line:	32
	; >>>>> printString("it"); 
	mov	ax, L_lab5app_2
	push	ax
	call	printString
	add	sp, 2
	; >>>>> Line:	33
	; >>>>> YKSemPost(SSemPtr); 
	push	word [SSemPtr]
	call	YKSemPost
	add	sp, 2
	; >>>>> Line:	35
	; >>>>> YKSemPend(WSemPtr); 
	push	word [WSemPtr]
	call	YKSemPend
	add	sp, 2
	; >>>>> Line:	36
	; >>>>> printString("works"); 
	mov	ax, L_lab5app_3
	push	ax
	call	printString
	add	sp, 2
	; >>>>> Line:	37
	; >>>>> YKSemPost(PSemPtr); 
	push	word [PSemPtr]
	call	YKSemPost
	add	sp, 2
L_lab5app_7:
	jmp	L_lab5app_6
L_lab5app_8:
	mov	sp, bp
	pop	bp
	ret
L_lab5app_4:
	push	bp
	mov	bp, sp
	jmp	L_lab5app_5
	ALIGN	2
TaskSpace:
	; >>>>> Line:	42
	; >>>>> { 
	jmp	L_lab5app_10
L_lab5app_11:
	; >>>>> Line:	43
	; >>>>> while (1) 
	jmp	L_lab5app_13
L_lab5app_12:
	; >>>>> Line:	45
	; >>>>> YKSemPend(SSemPtr); 
	push	word [SSemPtr]
	call	YKSemPend
	add	sp, 2
	; >>>>> Line:	46
	; >>>>> printChar(' '); 
	mov	al, 32
	push	ax
	call	printChar
	add	sp, 2
	; >>>>> Line:	47
	; >>>>> YKSemPost(WSemPtr); 
	push	word [WSemPtr]
	call	YKSemPost
	add	sp, 2
L_lab5app_13:
	jmp	L_lab5app_12
L_lab5app_14:
	mov	sp, bp
	pop	bp
	ret
L_lab5app_10:
	push	bp
	mov	bp, sp
	jmp	L_lab5app_11
L_lab5app_16:
	DB	"!",'"',0xD,0xA,0
	ALIGN	2
TaskPunc:
	; >>>>> Line:	52
	; >>>>> { 
	jmp	L_lab5app_17
L_lab5app_18:
	; >>>>> Line:	53
	; >>>>> while (1) 
	jmp	L_lab5app_20
L_lab5app_19:
	; >>>>> Line:	55
	; >>>>> YKSemPend(PSemPtr); 
	push	word [PSemPtr]
	call	YKSemPend
	add	sp, 2
	; >>>>> Line:	56
	; >>>>> printChar('"'); 
	mov	al, 34
	push	ax
	call	printChar
	add	sp, 2
	; >>>>> Line:	57
	; >>>>> YKSemPost(WSemPtr); 
	push	word [WSemPtr]
	call	YKSemPost
	add	sp, 2
	; >>>>> Line:	59
	; >>>>> YKSemPend(PSemP 
	push	word [PSemPtr]
	call	YKSemPend
	add	sp, 2
	; >>>>> Line:	60
	; >>>>> printChar(','); 
	mov	al, 44
	push	ax
	call	printChar
	add	sp, 2
	; >>>>> Line:	61
	; >>>>> YKSemPost(SSemPtr); 
	push	word [SSemPtr]
	call	YKSemPost
	add	sp, 2
	; >>>>> Line:	63
	; >>>>> YKSemPend(PSemPtr); 
	push	word [PSemPtr]
	call	YKSemPend
	add	sp, 2
	; >>>>> Line:	64
	; >>>>> printString("!\"\r\n"); 
	mov	ax, L_lab5app_16
	push	ax
	call	printString
	add	sp, 2
	; >>>>> Line:	65
	; >>>>> YKSemPost(PSemPtr); 
	push	word [PSemPtr]
	call	YKSemPost
	add	sp, 2
	; >>>>> Line:	67
	; >>>>> YKDelayTask(6); 
	mov	ax, 6
	push	ax
	call	YKDelayTask
	add	sp, 2
L_lab5app_20:
	jmp	L_lab5app_19
L_lab5app_21:
	mov	sp, bp
	pop	bp
	ret
L_lab5app_17:
	push	bp
	mov	bp, sp
	jmp	L_lab5app_18
	ALIGN	2
TaskPrime:
	; >>>>> Line:	72
	; >>>>> { 
	jmp	L_lab5app_23
L_lab5app_24:
	; >>>>> Line:	77
	; >>>>> while (1) 
	mov	word [bp-2], 1001
	; >>>>> Line:	77
	; >>>>> while (1) 
	jmp	L_lab5app_26
L_lab5app_25:
	; >>>>> Line:	79
	; >>>>> YKSemPend(NSemPtr); 
	push	word [NSemPtr]
	call	YKSemPend
	add	sp, 2
	; >>>>> Line:	82
	; >>>>> lncnt = 0; 
	mov	word [bp-8], 0
	; >>>>> Line:	83
	; >>>>> endval = curval + 500; 
	mov	ax, word [bp-2]
	add	ax, 500
	mov	word [bp-10], ax
	; >>>>> Line:	84
	; >>>>> for ( ; curval < endval; curval += 2) 
	jmp	L_lab5app_29
L_lab5app_28:
	; >>>>> Line:	86
	; >>>>> flag = 0; 
	mov	word [bp-6], 0
	; >>>>> Line:	87
	; >>>>> for (j = 3; (j*j) < curval; j += 2) 
	mov	word [bp-4], 3
	jmp	L_lab5app_33
L_lab5app_32:
	; >>>>> Line:	89
	; >>>>> dl 
	mov	ax, word [bp-2]
	cwd
	idiv	word [bp-4]
	mov	ax, dx
	test	ax, ax
	jne	L_lab5app_36
	; >>>>> Line:	91
	; >>>>> flag = 1; 
	mov	word [bp-6], 1
	; >>>>> Line:	92
	; >>>>> break; 
	jmp	L_lab5app_34
L_lab5app_36:
L_lab5app_35:
	add	word [bp-4], 2
L_lab5app_33:
	mov	ax, word [bp-4]
	imul	word [bp-4]
	mov	dx, word [bp-2]
	cmp	dx, ax
	jg	L_lab5app_32
L_lab5app_34:
	; >>>>> Line:	95
	; >>>>> if (!flag) 
	mov	ax, word [bp-6]
	test	ax, ax
	jne	L_lab5app_37
	; >>>>> Line:	97
	; >>>>> printChar(' '); 
	mov	al, 32
	push	ax
	call	printChar
	add	sp, 2
	; >>>>> Line:	98
	; >>>>> printInt(curval); 
	push	word [bp-2]
	call	printInt
	add	sp, 2
	; >>>>> Line:	99
	; >>>>> lncnt++; 
	inc	word [bp-8]
	; >>>>> Line:	100
	; >>>>> if (lncnt > 9) 
	cmp	word [bp-8], 9
	jle	L_lab5app_38
	; >>>>> Line:	102
	; >>>>> printNewLine(); 
	call	printNewLine
	; >>>>> Line:	103
	; >>>>> lncnt = 0; 
	mov	word [bp-8], 0
L_lab5app_38:
L_lab5app_37:
L_lab5app_31:
	add	word [bp-2], 2
L_lab5app_29:
	mov	ax, word [bp-10]
	cmp	ax, word [bp-2]
	jg	L_lab5app_28
L_lab5app_30:
	; >>>>> Line:	107
	; >>>>> printNewLine(); 
	call	printNewLine
L_lab5app_26:
	jmp	L_lab5app_25
L_lab5app_27:
	mov	sp, bp
	pop	bp
	ret
L_lab5app_23:
	push	bp
	mov	bp, sp
	sub	sp, 10
	jmp	L_lab5app_24
L_lab5app_44:
	DB	"% >>>>>",0xD,0xA,0
L_lab5app_43:
	DB	", CPU usage: ",0
L_lab5app_42:
	DB	"<<<<< Context switches: ",0
L_lab5app_41:
	DB	"Determining CPU capacity",0xD,0xA,0
L_lab5app_40:
	DB	"Welcome to the YAK kernel",0xD,0xA,0
	ALIGN	2
TaskStat:
	; >>>>> Line:	112
	; >>>>> { 
	jmp	L_lab5app_45
L_lab5app_46:
	; >>>>> Line:	116
	; >>>>> YKDelayTask(1); 
	mov	ax, 1
	push	ax
	call	YKDelayTask
	add	sp, 2
	; >>>>> Line:	117
	; >>>>> printString("Welcome to the YAK kernel\r\n"); 
	mov	ax, L_lab5app_40
	push	ax
	call	printString
	add	sp, 2
	; >>>>> Line:	118
	; >>>>> printString("Determining CPU capacity\r\n"); 
	mov	ax, L_lab5app_41
	push	ax
	call	printString
	add	sp, 2
	; >>>>> Line:	119
	; >>>>> YKDelayTask(1); 
	mov	ax, 1
	push	ax
	call	YKDelayTask
	add	sp, 2
	; >>>>> Line:	120
	; >>>>> YKIdleCount = 0; 
	mov	word [YKIdleCount], 0
	; >>>>> Line:	121
	; >>>>> YKDelayTask(5); 
	mov	ax, 5
	push	ax
	call	YKDelayTask
	add	sp, 2
	; >>>>> Line:	122
	; >>>>> max = YKIdleCount / 25; 
	mov	ax, word [YKIdleCount]
	xor	dx, dx
	mov	cx, 25
	div	cx
	mov	word [bp-2], ax
	; >>>>> Line:	123
	; >>>>> YKIdleCount = 0; 
	mov	word [YKIdleCount], 0
	; >>>>> Line:	125
	; >>>>> YKNewTask(TaskPrime, (void *) &TaskPRMStk[512], 32); 
	mov	al, 32
	push	ax
	mov	ax, (TaskPRMStk+1024)
	push	ax
	mov	ax, TaskPrime
	push	ax
	call	YKNewTask
	add	sp, 6
	; >>>>> Line:	126
	; >>>>> YKNewTask(TaskWord, (void *) &TaskWStk[512], 10); 
	mov	al, 10
	push	ax
	mov	ax, (TaskWStk+1024)
	push	ax
	mov	ax, TaskWord
	push	ax
	call	YKNewTask
	add	sp, 6
	; >>>>> Line:	127
	; >>>>> YKNewTask(TaskSpace, (void *) &TaskSStk[512], 11); 
	mov	al, 11
	push	ax
	mov	ax, (TaskSStk+1024)
	push	ax
	mov	ax, TaskSpace
	push	ax
	call	YKNewTask
	add	sp, 6
	; >>>>> Line:	128
	; >>>>> YKNewTask(TaskPunc, (void *) &TaskPStk[512], 12); 
	mov	al, 12
	push	ax
	mov	ax, (TaskPStk+1024)
	push	ax
	mov	ax, TaskPunc
	push	ax
	call	YKNewTask
	add	sp, 6
	; >>>>> Line:	130
	; >>>>> while (1) 
	jmp	L_lab5app_48
L_lab5app_47:
	; >>>>> Line:	132
	; >>>>> alize(); 
	mov	ax, 20
	push	ax
	call	YKDelayTask
	add	sp, 2
	; >>>>> Line:	134
	; >>>>> YKEnterMutex(); 
	call	YKEnterMutex
	; >>>>> Line:	135
	; >>>>> switchCount = YKCtxSwCount; 
	mov	ax, word [YKCtxSwCount]
	mov	word [bp-4], ax
	; >>>>> Line:	136
	; >>>>> idleCount = YKIdleCount; 
	mov	ax, word [YKIdleCount]
	mov	word [bp-6], ax
	; >>>>> Line:	137
	; >>>>> YKExitMutex(); 
	call	YKExitMutex
	; >>>>> Line:	139
	; >>>>> printString ("<<<<< Context switches: "); 
	mov	ax, L_lab5app_42
	push	ax
	call	printString
	add	sp, 2
	; >>>>> Line:	140
	; >>>>> printInt((int)switchCount); 
	push	word [bp-4]
	call	printInt
	add	sp, 2
	; >>>>> Line:	141
	; >>>>> printString(", CPU usage: "); 
	mov	ax, L_lab5app_43
	push	ax
	call	printString
	add	sp, 2
	; >>>>> Line:	142
	; >>>>> tmp = (int) (idleCount/max); 
	mov	ax, word [bp-6]
	xor	dx, dx
	div	word [bp-2]
	mov	word [bp-8], ax
	; >>>>> Line:	143
	; >>>>> printInt(100-tmp); 
	mov	ax, 100
	sub	ax, word [bp-8]
	push	ax
	call	printInt
	add	sp, 2
	; >>>>> Line:	144
	; >>>>> printString("% >>>>>\r\n"); 
	mov	ax, L_lab5app_44
	push	ax
	call	printString
	add	sp, 2
	; >>>>> Line:	146
	; >>>>> YKEnterMutex(); 
	call	YKEnterMutex
	; >>>>> Line:	147
	; >>>>> YKCtxSwCount = 0; 
	mov	word [YKCtxSwCount], 0
	; >>>>> Line:	148
	; >>>>> YKIdleCount = 0; 
	mov	word [YKIdleCount], 0
	; >>>>> Line:	149
	; >>>>> YKExitMutex(); 
	call	YKExitMutex
L_lab5app_48:
	jmp	L_lab5app_47
L_lab5app_49:
	mov	sp, bp
	pop	bp
	ret
L_lab5app_45:
	push	bp
	mov	bp, sp
	sub	sp, 8
	jmp	L_lab5app_46
	ALIGN	2
main:
	; >>>>> Line:	154
	; >>>>> { 
	jmp	L_lab5app_51
L_lab5app_52:
	; >>>>> Line:	155
	; >>>>> YKInitialize(); 
	call	YKInitialize
	; >>>>> Line:	158
	; >>>>> PSemPtr = YK 
	mov	ax, 1
	push	ax
	call	YKSemCreate
	add	sp, 2
	mov	word [PSemPtr], ax
	; >>>>> Line:	159
	; >>>>> SSemPtr = YKSemCreate(0); 
	xor	ax, ax
	push	ax
	call	YKSemCreate
	add	sp, 2
	mov	word [SSemPtr], ax
	; >>>>> Line:	160
	; >>>>> WSemPtr = YKSemCreate(0); 
	xor	ax, ax
	push	ax
	call	YKSemCreate
	add	sp, 2
	mov	word [WSemPtr], ax
	; >>>>> Line:	161
	; >>>>> NSemPtr = YKSemCreate(0); 
	xor	ax, ax
	push	ax
	call	YKSemCreate
	add	sp, 2
	mov	word [NSemPtr], ax
	; >>>>> Line:	162
	; >>>>> YKNewTask(TaskStat, (void *) &TaskStatStk[512], 30); 
	mov	al, 30
	push	ax
	mov	ax, (TaskStatStk+1024)
	push	ax
	mov	ax, TaskStat
	push	ax
	call	YKNewTask
	add	sp, 6
	; >>>>> Line:	164
	; >>>>> YKRun(); 
	call	YKRun
	mov	sp, bp
	pop	bp
	ret
L_lab5app_51:
	push	bp
	mov	bp, sp
	jmp	L_lab5app_52
	ALIGN	2
TaskWStk:
	TIMES	1024 db 0
TaskSStk:
	TIMES	1024 db 0
TaskPStk:
	TIMES	1024 db 0
TaskStatStk:
	TIMES	1024 db 0
TaskPRMStk:
	TIMES	1024 db 0
PSemPtr:
	TIMES	2 db 0
SSemPtr:
	TIMES	2 db 0
WSemPtr:
	TIMES	2 db 0
NSemPtr:
	TIMES	2 db 0
